/***************************************************************************//**
 * @file
 * @brief Tokens for the WWAH App Event Retry Manager plugin.
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#if !defined(SL_CATALOG_TOKEN_MANAGER_PRESENT)
#include "sl_token_manager_api.h"
#include "sl_token_manager_defines.h"
#endif

#include "wwah-app-event-retry-manager.h"
#include "config/wwah-app-event-retry-manager-config.h"
#if (SL_ZIGBEE_AF_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_UNLIMITED_RETRIES == 1)
#define UNLIMITED_RETRIES
#endif

/**
 * Custom Application Tokens
 */
// The following parameters are to persist the App Event Retry configuration.
#define CREATOR_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED                   (0x001B)
#define CREATOR_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S      (0x001C)
#define CREATOR_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO      (0x001D)
#define CREATOR_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S        (0x001E)
#define CREATOR_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS   (0x001F)

// The following parameters are to persist the App Event Retry configuration.
#define NVM3KEY_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED                   (NVM3KEY_DOMAIN_USER | 0x001B)
#define NVM3KEY_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S      (NVM3KEY_DOMAIN_USER | 0x001C)
#define NVM3KEY_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO      (NVM3KEY_DOMAIN_USER | 0x001D)
#define NVM3KEY_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S        (NVM3KEY_DOMAIN_USER | 0x001E)
#define NVM3KEY_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS   (NVM3KEY_DOMAIN_USER | 0x001F)

// The following parameters are to persist the App Event Retry configuration.
#define COMMON_TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED                     SL_TOKEN_GET_DYNAMIC_TOKEN((SL_TOKEN_NVM3_REGION_USER | 0x001B), 0)
#define COMMON_TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S        SL_TOKEN_GET_DYNAMIC_TOKEN((SL_TOKEN_NVM3_REGION_USER | 0x001C), 0)
#define COMMON_TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO        SL_TOKEN_GET_DYNAMIC_TOKEN((SL_TOKEN_NVM3_REGION_USER | 0x001D), 0)
#define COMMON_TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S          SL_TOKEN_GET_DYNAMIC_TOKEN((SL_TOKEN_NVM3_REGION_USER | 0x001E), 0)
#define COMMON_TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS     SL_TOKEN_GET_DYNAMIC_TOKEN((SL_TOKEN_NVM3_REGION_USER | 0x001F), 0)

#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED_DEFAULT 0x01
#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S_DEFAULT SL_ZIGBEE_AF_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_SEC
#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO_DEFAULT SL_ZIGBEE_AF_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_SEQUENCE_COMMON_RATIO
#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S_DEFAULT SL_ZIGBEE_AF_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_SEC

#if defined(UNLIMITED_RETRIES)
#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS_DEFAULT 0xFF
#else
#define TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS_DEFAULT SL_ZIGBEE_AF_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_RETRY_ATTEMPTS
#endif

#ifdef DEFINETOKENS
// Define the actual token storage information here
DEFINE_BASIC_TOKEN(PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED, uint8_t, TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_ENABLED_DEFAULT)
DEFINE_BASIC_TOKEN(PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S, uint8_t, TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_FIRST_BACKOFF_TIME_S_DEFAULT)
DEFINE_BASIC_TOKEN(PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO, uint8_t, TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_BACKOFF_COMMON_RATIO_DEFAULT)
DEFINE_BASIC_TOKEN(PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S, uint32_t, TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_BACKOFF_TIME_S_DEFAULT)
DEFINE_BASIC_TOKEN(PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS, uint8_t, TOKEN_PLUGIN_WWAH_APP_EVENT_RETRY_MANAGER_MAX_REDELIVERY_ATTEMPTS_DEFAULT)
#endif  // DEFINETOKENS
