/***************************************************************************//**
 * @file
 * @brief Defines for the Zigbee Event Logger component, which describes various
 * events that can be recorded and retrieved for user inspection.
 *******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
//
// *** Generated file. Do not edit! ***
// Generated by: generate-zigbee-logger-files.py -y zigbee_logger.yaml

#include "../../include/af.h"
#include "stack/include/zigbee-event-logger-gen.h"
#include "zigbee-event-logger-internal.h"
#include "compact-logger.h"

void sl_zigbee_af_zig_bee_event_logger_add_boot_event(uint32_t bootCount, uint16_t resetType)
{
  // Values for resetType are found in micro.h and reset-def.h.
  uint8_t bootEventData[SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_LENGTH];
  uint8_t *ptr = bootEventData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_BASE)) {
    return;
  }

  ptr = addUint32_t(ptr, bootCount);
  ptr = addUint16_t(ptr, resetType);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_LENGTH,
                                  bootEventData);
}

void sl_zigbee_af_zig_bee_event_logger_add_join_network(sl_802154_pan_id_t panId, uint8_t channelNumber, uint8_t page, uint8_t *extendedPanId)
{
  uint8_t joinNetworkData[SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_LENGTH];
  uint8_t *ptr = joinNetworkData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_BASE)) {
    return;
  }

  ptr = addUint16_t(ptr, panId);
  ptr = addUint8_t(ptr, channelNumber);
  ptr = addUint8_t(ptr, page);
  ptr = addArray(ptr, extendedPanId, EXTENDED_PAN_ID_SIZE);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_LENGTH,
                                  joinNetworkData);
}

void sl_zigbee_af_zig_bee_event_logger_add_trust_center_rejoin(uint32_t channelMask, sl_zigbee_rejoin_reason_t reason)
{
  uint8_t trustCenterRejoinData[SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_LENGTH];
  uint8_t *ptr = trustCenterRejoinData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint32_t(ptr, channelMask);
  ptr = addUint8_t(ptr, reason);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_LENGTH,
                                  trustCenterRejoinData);
}

void sl_zigbee_af_zig_bee_event_logger_add_secure_rejoin(uint32_t channelMask, sl_zigbee_rejoin_reason_t reason)
{
  uint8_t secureRejoinData[SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_LENGTH];
  uint8_t *ptr = secureRejoinData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint32_t(ptr, channelMask);
  ptr = addUint8_t(ptr, reason);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_LENGTH,
                                  secureRejoinData);
}

void sl_zigbee_af_zig_bee_event_logger_add_leave_without_rejoin(sl_802154_short_addr_t sourceNode, sl_zigbee_leave_reason_t reason)
{
  uint8_t leaveWithoutRejoinData[SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_LENGTH];
  uint8_t *ptr = leaveWithoutRejoinData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, sourceNode);
  ptr = addUint8_t(ptr, reason);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_LENGTH,
                                  leaveWithoutRejoinData);
}

void sl_zigbee_af_zig_bee_event_logger_add_leave_with_rejoin(sl_802154_short_addr_t sourceNode, sl_zigbee_leave_reason_t reason)
{
  uint8_t leaveWithRejoinData[SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_LENGTH];
  uint8_t *ptr = leaveWithRejoinData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, sourceNode);
  ptr = addUint8_t(ptr, reason);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_LENGTH,
                                  leaveWithRejoinData);
}

void sl_zigbee_af_zig_bee_event_logger_add_trust_center_link_key_change(void)
{
  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_SECURITY)) {
    return;
  }

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_LENGTH,
                                  NULL);
}

void sl_zigbee_af_zig_bee_event_logger_add_network_key_sequence_change(uint8_t sequence)
{
  uint8_t networkKeySequenceChangeData[SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_LENGTH];
  uint8_t *ptr = networkKeySequenceChangeData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_SECURITY)) {
    return;
  }

  ptr = addUint8_t(ptr, sequence);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_LENGTH,
                                  networkKeySequenceChangeData);
}

void sl_zigbee_af_zig_bee_event_logger_add_reset(uint8_t resetCode, uint8_t extendedReason)
{
  uint8_t resetData[SL_ZIGBEE_LOGGER_ZIGBEE_RESET_LENGTH];
  uint8_t *ptr = resetData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_SECURITY)) {
    return;
  }

  ptr = addUint8_t(ptr, resetCode);
  ptr = addUint8_t(ptr, extendedReason);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_RESET_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_RESET_LENGTH,
                                  resetData);
}

void sl_zigbee_af_zig_bee_event_logger_add_channel_change(uint8_t page, uint8_t channel)
{
  uint8_t channelChangeData[SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_LENGTH];
  uint8_t *ptr = channelChangeData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_MAC)) {
    return;
  }

  ptr = addUint8_t(ptr, page);
  ptr = addUint8_t(ptr, channel);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_LENGTH,
                                  channelChangeData);
}

void sl_zigbee_af_zig_bee_event_logger_add_parent_change(sl_802154_short_addr_t parentNodeId, sl_802154_long_addr_t parentEui64)
{
  uint8_t parentChangeData[SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_LENGTH];
  uint8_t *ptr = parentChangeData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, parentNodeId);
  ptr = addArray(ptr, parentEui64, EUI64_SIZE);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_LENGTH,
                                  parentChangeData);
}

void sl_zigbee_af_zig_bee_event_logger_add_duty_cycle_change(sl_zigbee_duty_cycle_state_t state, sl_zigbee_duty_cycle_hecto_pct_t limitThreshold, sl_zigbee_duty_cycle_hecto_pct_t criticalThreshold, sl_zigbee_duty_cycle_hecto_pct_t suspendedLimit)
{
  uint8_t dutyCycleChangeData[SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_LENGTH];
  uint8_t *ptr = dutyCycleChangeData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint8_t(ptr, state);
  ptr = addUint16_t(ptr, limitThreshold);
  ptr = addUint16_t(ptr, criticalThreshold);
  ptr = addUint16_t(ptr, suspendedLimit);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_LENGTH,
                                  dutyCycleChangeData);
}

void sl_zigbee_af_zig_bee_event_logger_add_child_added(sl_802154_short_addr_t childNodeId, sl_802154_long_addr_t childEui64)
{
  uint8_t childAddedData[SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_LENGTH];
  uint8_t *ptr = childAddedData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, childNodeId);
  ptr = addArray(ptr, childEui64, EUI64_SIZE);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_LENGTH,
                                  childAddedData);
}

void sl_zigbee_af_zig_bee_event_logger_add_child_removed(sl_802154_short_addr_t childNodeId, sl_802154_long_addr_t childEui64)
{
  uint8_t childRemovedData[SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_LENGTH];
  uint8_t *ptr = childRemovedData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, childNodeId);
  ptr = addArray(ptr, childEui64, EUI64_SIZE);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_LENGTH,
                                  childRemovedData);
}

void sl_zigbee_af_zig_bee_event_logger_add_child_timed_out(sl_802154_short_addr_t childNodeId, sl_802154_long_addr_t childEui64)
{
  uint8_t childTimedOutData[SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_LENGTH];
  uint8_t *ptr = childTimedOutData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint16_t(ptr, childNodeId);
  ptr = addArray(ptr, childEui64, EUI64_SIZE);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_LENGTH,
                                  childTimedOutData);
}

void sl_zigbee_af_zig_bee_event_logger_add_stack_status(sl_status_t status)
{
  uint8_t stackStatusData[SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_LENGTH];
  uint8_t *ptr = stackStatusData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_NETWORK)) {
    return;
  }

  ptr = addUint32_t(ptr, status);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_LENGTH,
                                  stackStatusData);
}

void sl_zigbee_af_zig_bee_event_logger_add_time_sync(uint32_t utcTime, uint32_t secondsSinceBoot)
{
  uint8_t timeSyncData[SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_LENGTH];
  uint8_t *ptr = timeSyncData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_BASE)) {
    return;
  }

  ptr = addUint32_t(ptr, utcTime);
  ptr = addUint32_t(ptr, secondsSinceBoot);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_LENGTH,
                                  timeSyncData);
}

void sl_zigbee_af_zig_bee_event_logger_add_trust_center_join_decision(sl_802154_short_addr_t nodeId, uint8_t decision)
{
  uint8_t trustCenterJoinDecisionData[SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_LENGTH];
  uint8_t *ptr = trustCenterJoinDecisionData;

  if (!sl_zigbee_af_compact_logger_check_facility_and_severity(SL_ZIGBEE_AF_PLUGIN_COMPACT_LOGGER_SEVERITY_NOTICE,
                                                               SL_ZIGBEE_LOGGER_ZIGBEE_FACILITY_SECURITY)) {
    return;
  }

  ptr = addUint16_t(ptr, nodeId);
  ptr = addUint8_t(ptr, decision);

  sl_zigbee_af_compact_logger_add(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_ID,
                                  SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_LENGTH,
                                  trustCenterJoinDecisionData);
}
