/***************************************************************************//**
 * @file
 * @brief Defines for the Zigbee Event Logger component, which describes various
 * events that can be recorded and retrieved for user inspection.
 *******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
//
// *** Generated file. Do not edit! ***
// Generated by: generate-zigbee-logger-files.py -y zigbee_logger.yaml

#ifndef _ZIGBEE_EVENT_LOGGER_PRINT_GEN_H_

typedef bool (printFunction)(uint8_t *data, uint16_t dataLength);

/** @brief Prints the hexadecimal data associated with the passed in event.
 * @param data  The event data.
 * @param dataLength  The event data length.
 * @return bool Always true.
 * @note This function is only to be called if the user wishes to see the hex data
 * stored for this event. The API sl_zigbee_af_zig_bee_event_logger_lookup_print_function
 * exists for fetching the API to print the event data in a human-readible format. The
 * sl_zigbee_af_zig_bee_event_logger_lookup_print_function API only returns a function
 * that display human-readible output if the SL_ZIGBEE_AF_PLUGIN_ZIGBEE_EVENT_LOGGER_INCLUDE_STRINGS_IN_LOGS
 * option is enabled in the Zigbee Event Logger component. See zigbee-event-logger-cli.c for
 * an example.
 */
bool sl_zigbee_af_zig_bee_event_logger_print_hex_data(uint8_t *data, uint16_t dataLength);

/** @brief Retrieves the print function to display human-readible event data.
 * @param type  An event data as defined in the sl_zigbee_zigbee_logger_event_types_t enumeration.
 * @return printFunction A function handler of type printFunction.
 * @note This function returns a handler to a function. The user is expected to then call the
 * handler with the hexadecimal data and data length to get human-readible output.
 * See zigbee-event-logger-cli.c for an example.
 */
printFunction *sl_zigbee_af_zig_bee_event_logger_lookup_print_function(sl_zigbee_zigbee_logger_event_types_t type);

#endif  // #ifndef _ZIGBEE_EVENT_LOGGER_PRINT_GEN_H_
