/***************************************************************************//**
 * @file
 * @brief Defines for the Zigbee Event Logger component, which describes various
 * events that can be recorded and retrieved for user inspection.
 *******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
//
// *** Generated file. Do not edit! ***
// Generated by: generate-zigbee-logger-files.py -y zigbee_logger.yaml

#include "../../include/af.h"
#include "stack/include/zigbee-event-logger-gen.h"
#include "zigbee-event-logger-internal.h"
#include "zigbee-event-logger-print-gen.h"
#include "app/framework/util/print.h"

bool sl_zigbee_af_zig_bee_event_logger_print_hex_data(uint8_t *data, uint16_t dataLength)
{
  sl_zigbee_af_print_buffer(0xFFFF, data, dataLength, FALSE);
  sl_zigbee_af_core_print("\n");
  return true;
}

#if defined(INCLUDE_STRINGS_IN_LOGS)

#define SHORT 0
#define LONG 1

#if SL_ZIGBEE_AF_PLUGIN_ZIGBEE_EVENT_LOGGER_PRINT_STRING_LENGTH == LONG
  #define SL_ZIGBEE_LOGGER_ZIGBEE_LONG_STRINGS
#elif SL_ZIGBEE_AF_PLUGIN_ZIGBEE_EVENT_LOGGER_PRINT_STRING_LENGTH == SHORT
  #define SL_ZIGBEE_LOGGER_ZIGBEE_SHORT_STRINGS
#endif

static bool printBootEvent(uint8_t *data, uint16_t dataLength);
static bool printJoinNetwork(uint8_t *data, uint16_t dataLength);
static bool printTrustCenterRejoin(uint8_t *data, uint16_t dataLength);
static bool printSecureRejoin(uint8_t *data, uint16_t dataLength);
static bool printLeaveWithoutRejoin(uint8_t *data, uint16_t dataLength);
static bool printLeaveWithRejoin(uint8_t *data, uint16_t dataLength);
static bool printTrustCenterLinkKeyChange(uint8_t *data, uint16_t dataLength);
static bool printNetworkKeySequenceChange(uint8_t *data, uint16_t dataLength);
static bool printReset(uint8_t *data, uint16_t dataLength);
static bool printChannelChange(uint8_t *data, uint16_t dataLength);
static bool printParentChange(uint8_t *data, uint16_t dataLength);
static bool printDutyCycleChange(uint8_t *data, uint16_t dataLength);
static bool printChildAdded(uint8_t *data, uint16_t dataLength);
static bool printChildRemoved(uint8_t *data, uint16_t dataLength);
static bool printChildTimedOut(uint8_t *data, uint16_t dataLength);
static bool printStackStatus(uint8_t *data, uint16_t dataLength);
static bool printTimeSync(uint8_t *data, uint16_t dataLength);
static bool printTrustCenterJoinDecision(uint8_t *data, uint16_t dataLength);

typedef struct {
  sl_zigbee_zigbee_logger_event_types_t type;
  printFunction *pfunc;
  const char* string;
} EmberZigbeeLoggerIdToPrint;

#ifdef SL_ZIGBEE_LOGGER_ZIGBEE_LONG_STRINGS
static EmberZigbeeLoggerIdToPrint idToPrint[] = {
  { SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_ID,
    printBootEvent,
    "Boot event. Boot Count: %d. Type:0x%04X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_ID,
    printJoinNetwork,
    "Joining the network on PAN ID: 0x%04X, channel: %d, page: %d, extPanId: 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_ID,
    printTrustCenterRejoin,
    "Trust Center Rejoin channel mask: 0x%08X, reason: 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_ID,
    printSecureRejoin,
    "Secure Rejoin channel mask: 0x%08X, reason: 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_ID,
    printLeaveWithoutRejoin,
    "Leave Network Without Rejoin from node ID 0x%04X, reason: 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_ID,
    printLeaveWithRejoin,
    "Leave Network With Rejoin from node ID 0x%04X, reason: 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_ID,
    printTrustCenterLinkKeyChange,
    "Trust Center Link Key Change" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_ID,
    printNetworkKeySequenceChange,
    "Network Key changed to sequence num: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_RESET_ID,
    printReset,
    "Reset due to Ember Reset Info: %d, extended reset: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_ID,
    printChannelChange,
    "Changed channel to page: %d, channel: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_ID,
    printParentChange,
    "Changed to new parent 0x%04X, eui: 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_ID,
    printDutyCycleChange,
    "Duty Cycle Change state %d, limit %d, critical %d, susp %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_ID,
    printChildAdded,
    "Child Added 0x%04X, eui: 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_ID,
    printChildRemoved,
    "Child Removed 0x%04X, eui: 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_ID,
    printChildTimedOut,
    "Child Timed Out 0x%04X eui: 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_ID,
    printStackStatus,
    "Stack Status Event 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_ID,
    printTimeSync,
    "UTC Time Sync'd, ZigBee UTC Time %d, seconds since boot %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_ID,
    printTrustCenterJoinDecision,
    "Trust Center Join Decision for 0x%04X: %02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID, NULL, NULL }
};
#elif defined SL_ZIGBEE_LOGGER_ZIGBEE_SHORT_STRINGS
static EmberZigbeeLoggerIdToPrint idToPrint[] = {
  { SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_ID,
    printBootEvent,
    "Boot Cnt: %d. Type: 0x%04X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_ID,
    printJoinNetwork,
    "Join panId:0x%04X, ch:%d, pg:%d, epan:0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_ID,
    printTrustCenterRejoin,
    "TC Rejoin ch mask:0x%08X, rsn:0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_ID,
    printSecureRejoin,
    "Sec Rejoin ch mask:0x%08X, rsn:0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_ID,
    printLeaveWithoutRejoin,
    "Leave No Rejoin node:0x%04X, rsn:0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_ID,
    printLeaveWithRejoin,
    "Leave Rejoin node:0x%04X, rsn:0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_ID,
    printTrustCenterLinkKeyChange,
    "TC Link Key Change" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_ID,
    printNetworkKeySequenceChange,
    "Nwk Key seq num changed: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_RESET_ID,
    printReset,
    "Reset code: %d, ext: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_ID,
    printChannelChange,
    "Channel Change pg: %d chan: %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_ID,
    printParentChange,
    "Parent Change: 0x%04X, 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_ID,
    printDutyCycleChange,
    "Duty Cycle Change, st %d lim %d cr %d susp %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_ID,
    printChildAdded,
    "Child Added 0x%04X, 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_ID,
    printChildRemoved,
    "Child Removed 0x%04X, 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_ID,
    printChildTimedOut,
    "Child Tmout 0x%04X, 0x%02X%02X%02X%02X%02X%02X%02X%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_ID,
    printStackStatus,
    "Stack Status 0x%02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_ID,
    printTimeSync,
    "Time Sync, utcTime %d, sec %d" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_ID,
    printTrustCenterJoinDecision,
    "TC Join Decision for 0x%04X: %02X" },
  { SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID, NULL, NULL }
};
#endif

static const char* lookupFormatString(sl_zigbee_zigbee_logger_event_types_t type)
{
#if defined(SL_ZIGBEE_LOGGER_ZIGBEE_LONG_STRINGS) || defined(SL_ZIGBEE_LOGGER_ZIGBEE_SHORT_STRINGS)
  uint16_t i = 0;
  for (i = 0; i < SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID; i++) {
    if (type == idToPrint[i].type) {
      return idToPrint[i].string;
    }
    if (idToPrint[i].type == SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID) {
      return NULL;
    }
  }
#endif
  return NULL;
}

printFunction *sl_zigbee_af_zig_bee_event_logger_lookup_print_function(sl_zigbee_zigbee_logger_event_types_t type)
{
#if defined SL_ZIGBEE_LOGGER_ZIGBEE_LONG_STRINGS || defined SL_ZIGBEE_LOGGER_ZIGBEE_SHORT_STRINGS
  uint16_t i = 0;
  for (i = 0; i < SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID; i++) {
    if (type == idToPrint[i].type) {
      return idToPrint[i].pfunc;
    }
    if (idToPrint[i].type == SL_ZIGBEE_LOGGER_ZIGBEE_NULL_ID) {
      return NULL;
    }
  }
#endif
  return sl_zigbee_af_zig_bee_event_logger_print_hex_data;
}

static bool printBootEvent(uint8_t *data, uint16_t dataLength)
{
  uint32_t bootCount;
  uint16_t resetType;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_BOOT_EVENT_LENGTH) {
    return false;
  }
  bootCount = parseUint32_t(&data);
  resetType = parseUint16_t(&data);

  sl_zigbee_af_core_println(formattedString, bootCount, resetType);
  return true;
}

static bool printJoinNetwork(uint8_t *data, uint16_t dataLength)
{
  sl_802154_pan_id_t panId;
  uint8_t channelNumber;
  uint8_t page;
  uint8_t extendedPanId[EXTENDED_PAN_ID_SIZE];
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_JOIN_NETWORK_LENGTH) {
    return false;
  }
  panId = parseUint16_t(&data);
  channelNumber = parseUint8_t(&data);
  page = parseUint8_t(&data);
  parseArray(extendedPanId, &data, EXTENDED_PAN_ID_SIZE);

  sl_zigbee_af_core_println(formattedString, panId, channelNumber, page, extendedPanId[7], extendedPanId[6], extendedPanId[5], extendedPanId[4], extendedPanId[3], extendedPanId[2], extendedPanId[1], extendedPanId[0]);
  return true;
}

static bool printTrustCenterRejoin(uint8_t *data, uint16_t dataLength)
{
  uint32_t channelMask;
  sl_zigbee_rejoin_reason_t reason;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_REJOIN_LENGTH) {
    return false;
  }
  channelMask = parseUint32_t(&data);
  reason = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, channelMask, reason);
  return true;
}

static bool printSecureRejoin(uint8_t *data, uint16_t dataLength)
{
  uint32_t channelMask;
  sl_zigbee_rejoin_reason_t reason;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_SECURE_REJOIN_LENGTH) {
    return false;
  }
  channelMask = parseUint32_t(&data);
  reason = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, channelMask, reason);
  return true;
}

static bool printLeaveWithoutRejoin(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t sourceNode;
  sl_zigbee_leave_reason_t reason;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITHOUT_REJOIN_LENGTH) {
    return false;
  }
  sourceNode = parseUint16_t(&data);
  reason = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, sourceNode, reason);
  return true;
}

static bool printLeaveWithRejoin(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t sourceNode;
  sl_zigbee_leave_reason_t reason;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_LEAVE_WITH_REJOIN_LENGTH) {
    return false;
  }
  sourceNode = parseUint16_t(&data);
  reason = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, sourceNode, reason);
  return true;
}

static bool printTrustCenterLinkKeyChange(uint8_t *data, uint16_t dataLength)
{
  UNUSED_VAR(data);

  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_LINK_KEY_CHANGE_LENGTH) {
    return false;
  }

  sl_zigbee_af_core_println(formattedString);
  return true;
}

static bool printNetworkKeySequenceChange(uint8_t *data, uint16_t dataLength)
{
  uint8_t sequence;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_NETWORK_KEY_SEQUENCE_NUMBER_CHANGE_LENGTH) {
    return false;
  }
  sequence = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, sequence);
  return true;
}

static bool printReset(uint8_t *data, uint16_t dataLength)
{
  uint8_t resetCode;
  uint8_t extendedReason;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_RESET_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_RESET_LENGTH) {
    return false;
  }
  resetCode = parseUint8_t(&data);
  extendedReason = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, resetCode, extendedReason);
  return true;
}

static bool printChannelChange(uint8_t *data, uint16_t dataLength)
{
  uint8_t page;
  uint8_t channel;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_CHANNEL_CHANGE_LENGTH) {
    return false;
  }
  page = parseUint8_t(&data);
  channel = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, page, channel);
  return true;
}

static bool printParentChange(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t parentNodeId;
  sl_802154_long_addr_t parentEui64;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_PARENT_CHANGE_LENGTH) {
    return false;
  }
  parentNodeId = parseUint16_t(&data);
  parseArray(parentEui64, &data, EUI64_SIZE);

  sl_zigbee_af_core_println(formattedString, parentNodeId, parentEui64[7], parentEui64[6], parentEui64[5], parentEui64[4], parentEui64[3], parentEui64[2], parentEui64[1], parentEui64[0]);
  return true;
}

static bool printDutyCycleChange(uint8_t *data, uint16_t dataLength)
{
  sl_zigbee_duty_cycle_state_t state;
  sl_zigbee_duty_cycle_hecto_pct_t limitThreshold;
  sl_zigbee_duty_cycle_hecto_pct_t criticalThreshold;
  sl_zigbee_duty_cycle_hecto_pct_t suspendedLimit;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_DUTY_CYCLE_CHANGE_LENGTH) {
    return false;
  }
  state = parseUint8_t(&data);
  limitThreshold = parseUint16_t(&data);
  criticalThreshold = parseUint16_t(&data);
  suspendedLimit = parseUint16_t(&data);

  sl_zigbee_af_core_println(formattedString, state, limitThreshold, criticalThreshold, suspendedLimit);
  return true;
}

static bool printChildAdded(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t childNodeId;
  sl_802154_long_addr_t childEui64;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_ADDED_LENGTH) {
    return false;
  }
  childNodeId = parseUint16_t(&data);
  parseArray(childEui64, &data, EUI64_SIZE);

  sl_zigbee_af_core_println(formattedString, childNodeId, childEui64[7], childEui64[6], childEui64[5], childEui64[4], childEui64[3], childEui64[2], childEui64[1], childEui64[0]);
  return true;
}

static bool printChildRemoved(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t childNodeId;
  sl_802154_long_addr_t childEui64;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_REMOVED_LENGTH) {
    return false;
  }
  childNodeId = parseUint16_t(&data);
  parseArray(childEui64, &data, EUI64_SIZE);

  sl_zigbee_af_core_println(formattedString, childNodeId, childEui64[7], childEui64[6], childEui64[5], childEui64[4], childEui64[3], childEui64[2], childEui64[1], childEui64[0]);
  return true;
}

static bool printChildTimedOut(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t childNodeId;
  sl_802154_long_addr_t childEui64;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_CHILD_TIMED_OUT_LENGTH) {
    return false;
  }
  childNodeId = parseUint16_t(&data);
  parseArray(childEui64, &data, EUI64_SIZE);

  sl_zigbee_af_core_println(formattedString, childNodeId, childEui64[7], childEui64[6], childEui64[5], childEui64[4], childEui64[3], childEui64[2], childEui64[1], childEui64[0]);
  return true;
}

static bool printStackStatus(uint8_t *data, uint16_t dataLength)
{
  sl_status_t status;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_STACK_STATUS_LENGTH) {
    assert(false);
    return false;
  }
  status = parseUint32_t(&data);

  sl_zigbee_af_core_println(formattedString, status);
  return true;
}

static bool printTimeSync(uint8_t *data, uint16_t dataLength)
{
  uint32_t utcTime;
  uint32_t secondsSinceBoot;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_TIME_SYNC_LENGTH) {
    return false;
  }
  utcTime = parseUint32_t(&data);
  secondsSinceBoot = parseUint32_t(&data);

  sl_zigbee_af_core_println(formattedString, utcTime, secondsSinceBoot);
  return true;
}

static bool printTrustCenterJoinDecision(uint8_t *data, uint16_t dataLength)
{
  sl_802154_short_addr_t nodeId;
  uint8_t decision;
  const char *formattedString = lookupFormatString(SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_ID);
  if (formattedString == NULL || dataLength != SL_ZIGBEE_LOGGER_ZIGBEE_TRUST_CENTER_JOIN_DECISION_LENGTH) {
    return false;
  }
  nodeId = parseUint16_t(&data);
  decision = parseUint8_t(&data);

  sl_zigbee_af_core_println(formattedString, nodeId, decision);
  return true;
}

#else

printFunction *sl_zigbee_af_zig_bee_event_logger_lookup_print_function(sl_zigbee_zigbee_logger_event_types_t type)
{
  return sl_zigbee_af_zig_bee_event_logger_print_hex_data;
}

#endif  // #if defined(INCLUDE_STRINGS_IN_LOGS)
