---
template:
  connect_toolchains: &connect_toolchains
    - gcc
    - iar
    - segger
  connect_ides: &connect_ides
    - generic-template
    - iar-embedded-workbench
    - makefile-ide
    - simplicity-ide
    - visual-studio-code
    - visual-studio-code-cmake
#example specific settings
example:
#connect examples
  - path: example/connect_soc_empty/connect_soc_empty.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/connect_bt_dmp_soc_empty/connect_bt_dmp_soc_empty.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[mb]g22(?!l)
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[mb]g22(?!l).*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/connect_soc_direct_mode_device/connect_soc_direct_mode_device.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/connect_soc_ecdh_key_exchange/connect_soc_ecdh_key_exchange.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/connect_soc_mac_mode_device/connect_soc_mac_mode_device.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/sensor_sink/connect_soc_sensor/connect_soc_sensor.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
      - brd4180a
      - brd4180b
      - brd4181a
      - brd4181b
      - brd4181c
      - brd4311a
      - brd4311b
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/sensor_sink/connect_soc_sink/connect_soc_sink.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/light_switch/connect_soc_switch/connect_soc_switch.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
      - efr32[mb]g21
      - mgm21.*
    part_compatibility:
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*mgm(?!21).*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/light_switch/connect_bt_dmp_soc_light/connect_bt_dmp_soc_light.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g22(?!l)
      - mgm1[0-9]?.*
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm22.*
    part_blacklist_filter:
      - efr32bg22c112
      - efr32[mb]g21
      - mgm21.*
      - rm21.*
    part_compatibility:
      - .*(?!efr32bg22c112)efr32[mb]g22(?!l).*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*(?!mgm21)mgm.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: example/ncp-app/connect_ncp.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter:
      - efr32[mb]g21
      - efr32[fmb]g22(?!l)
      - efr32[fmz]g23
      - efr32[fmb]g24
      - efr32[fmb]g25
      - efr32[fmb]g26
      - efr32[fmb]g27
      - efr32[fmbz]g28
      - efr32[fmb]g29
      - mgm.*
      - rm21.*
      - fgm230s.*
    part_blacklist_filter:
      - efr32bg22c112
    part_compatibility:
      - .*efr32fg1v.*
      - .*(?!efr32bg14)efr32[fmb]g1[0-9]?p.*
      - .*efr32[mb]g21.*
      - .*(?!efr32bg22c112)efr32[fmb]g22(?!l).*
      - .*efr32[fmz]g23.*
      - .*(?!efr32bg22c112)efr32[fmb]g24.*
      - .*efr32[fmb]g25.*
      - .*efr32[fmb]g26.*
      - .*efr32[fmb]g27.*
      - .*efr32[fmbz]g28.*
      - .*efr32[fmb]g29.*
      - .*mgm.*
      - .*rm21.*
      - .*fgm230s.*
    board_blacklist:
      - brd2606a
    toolchain_compatibility: *connect_toolchains
    ide_compatibility: *connect_ides
  - path: ../../protocol/flex/app/mustang-app/mustang-app-simulation.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter: []
    part_blacklist_filter: []
    part_compatibility:
      - .*efr32.[zfmb]g.*
    board_blacklist:
      - brd2606a
  - path: ../../protocol/flex/app/mustang-app/mustang-app.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter: []
    part_blacklist_filter: []
    part_compatibility:
      - .*efr32.[zfmb]g.*
    board_blacklist:
      - brd2606a
  - path: ../../protocol/flex/app/ncp-app/connect_ncp_simulation.slcp
    # templates.xml::partCompatibility
    part_whitelist_filter: []
    part_blacklist_filter: []
    part_compatibility:
      - .*efr32.[zfmb]g.*
    board_blacklist:
      - brd2606a
