/***************************************************************************//**
 * @file
 * @brief Certificate Based Authentication and Pairing header
 *******************************************************************************
 * # License
 * <b>Copyright 2026 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/
#ifndef SL_BT_CBAP_H
#define SL_BT_CBAP_H

// -----------------------------------------------------------------------------
// Includes

#include <stdint.h>
#include <stddef.h>
#include "sl_status.h"
#include "sl_bt_cbap_key_id.h"

// -----------------------------------------------------------------------------
// Defines

#define SL_BT_CBAP_CERTIFICATE_MAX_SIZE     (700)

// -----------------------------------------------------------------------------
// Public function declarations

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************//**
 * Validate the provisioned certificate chain.
 *
 * @return SL_STATUS_OK on success, error code otherwise.
 *****************************************************************************/
sl_status_t sl_bt_cbap_init(void);

/**************************************************************************//**
 * Read a certificate from the persistent storage in DER format.
 *
 * The certificate is copied into the buffer owned by the caller, therefore it
 * stays valid until the caller overwrites it. The component keeps no reference
 * to the buffer. Each call reads the storage again, so callers that need the
 * certificate repeatedly should read it once and keep the copy.
 *
 * @param[in] id Storage ID of the certificate, for example
 *               SL_BT_CBAP_PSA_DEVICE_CERT. Note that the certificate IDs are
 *               distinct from the key IDs, such as SL_BT_CBAP_PSA_DEVICE_KEY.
 * @param[out] data Buffer receiving the certificate in DER format.
 * @param[out] data_len Length of the certificate written to @p data. Set to
 *                      zero if the certificate could not be read.
 * @param[in] max_len Size of the @p data buffer in bytes.
 *
 * @return SL_STATUS_OK on success, error code otherwise.
 *****************************************************************************/
sl_status_t sl_bt_cbap_get_certificate(cbap_key_id_t id,
                                       uint8_t *data,
                                       size_t *data_len,
                                       size_t max_len);

/***************************************************************************//**
 * Parse and validate remote certificate and extract remote public key.
 *
 * @param[in] remote_certificate_der Certificate from remote device in DER.
 * @param[in] remote_certificate_der_len Length of the remote certificate.
 *
 * @return SL_STATUS_OK if remote certificate is verified, error code otherwise.
 ******************************************************************************/
sl_status_t sl_bt_cbap_process_remote_cert(uint8_t *remote_certificate_der,
                                           uint32_t remote_certificate_der_len);

/***************************************************************************//**
 * Sign and combine OOB data.
 *
 * @param[in] device_random OOB data generated by the bt stack.
 * @param[in] device_confirm OOB data generated by the bt stack.
 * @param[out] output_data The signed OOB data
 * @param[out] output_len The signed OOB data length
 *
 * @return SL_STATUS_OK if OOB data signed, error code otherwise.
 ******************************************************************************/
sl_status_t sl_bt_cbap_sign_device_oob_data(uint8_t *device_random,
                                            uint8_t *device_confirm,
                                            uint8_t *output_data,
                                            size_t *output_len);

/***************************************************************************//**
 * Verify the remote device OOB data signature.
 *
 * @param[in] remote_random OOB data from remote device.
 * @param[in] remote_confirm OOB data from remote device.
 * @param[in] remote_oob_signature Remote OOB signature.
 *
 * @return SL_STATUS_OK if OOB data signature is OK, error code otherwise.
 ******************************************************************************/
sl_status_t sl_bt_cbap_verify_remote_oob_data(uint8_t *remote_random,
                                              uint8_t *remote_confirm,
                                              uint8_t *remote_oob_signature);

/***************************************************************************//**
 * Destroy the keys which were used during the CBAP process.
 *
 * @return SL_STATUS_OK if OK, error code otherwise.
 ******************************************************************************/
sl_status_t sl_bt_cbap_destroy_key(void);

#ifdef __cplusplus
};
#endif

#endif // SL_BT_CBAP_H
