/*
 * Silicon Laboratories Confidential
 * Copyright 2008-2013 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#ifndef _CMD_MAP_H_
#define _CMD_MAP_H_

#include "typedef.h"

/* This section contains command map declarations */
struct cmd_GENERIC_map {
  u8 CMD;
  u8 ARG1;
  u8 ARG2;
  u8 ARG3;
  u8 ARG4;
  u8 ARG5;
  u8 ARG6;
  u8 ARG7;
  u8 ARG8;
  u8 ARG9;
  u8 ARG10;
  u8 ARG11;
  u8 ARG12;
  u8 ARG13;
  u8 ARG14;
  u8 ARG15;
};

struct reply_GENERIC_map {
  u8 REPLY1;
  u8 REPLY2;
  u8 REPLY3;
  u8 REPLY4;
  u8 REPLY5;
  u8 REPLY6;
  u8 REPLY7;
  u8 REPLY8;
  u8 REPLY9;
  u8 REPLY10;
  u8 REPLY11;
  u8 REPLY12;
  u8 REPLY13;
  u8 REPLY14;
  u8 REPLY15;
  u8 REPLY16;
};

struct cmd_POWER_UP_map {
  u8 CMD;
  u8 BOOT_OPTIONS;
  u8 XTAL_OPTIONS;
  u32 XO_FREQ;
};

struct cmd_RAM_TEST_map {
  u8 CMD;
  u8 OPERATION;
  u16 CRC_START_ADDR;
  u16 CRC_SIZE;
  u8 RAM_TEST_FILL_BYTE;
};

struct reply_RAM_TEST_map {
  u8 RESULT;
  u16 OTP_CRC;
  u16 CRC;
};

struct cmd_PATCH_IMAGE_map {
  u8 CMD;
  u8 FLAGS;
  u16 CRC;
  u8 RESERVED1;
  u8 RESERVED2;
  u8 KEY1;
  u8 KEY2;
};

struct cmd_PATCH_ARGS_map {
  u8 CMD;
  u8 PIP;
  u8 RESERVED1;
  u16 ADDR;
  u8 RESERVED2;
  u16 CRC;
};

struct cmd_PATCH_COPY_map {
  u8 CMD;
  u16 SRC_ADDR;
  u16 DST_ADDR;
  u16 COUNT;
};

struct cmd_TEST_DATA_map {
  u8 CMD;
  u8 OFFSET;
};

struct reply_TEST_DATA_map {
  u8 TEST[16];
};

struct cmd_PATCH_COPY_2_map {
  u8 CMD;
  u16 SRC_ADDR;
  u16 DST_ADDR;
  u16 COUNT;
};

struct cmd_PATCH_DATA_map {
  u8 CMD;
  u8 DATA[8];
};

struct cmd_NOP_map {
  u8 CMD;
};

struct cmd_PART_INFO_map {
  u8 CMD;
};

struct reply_PART_INFO_map {
  u8 CHIPREV;
  u16 PART;
  u8 PBUILD;
  u16 ID;
  u8 CUSTOMER;
  u8 ROMID;
  u8 BOND;
};

struct cmd_FUNC_INFO_map {
  u8 CMD;
};

struct reply_FUNC_INFO_map {
  u8 REVEXT;
  u8 REVBRANCH;
  u8 REVINT;
  u16 PATCH;
  u8 FUNC;
  u8 SVNFLAGS;
  u32 SVNREV;
};

struct cmd_SET_PROPERTY_map {
  u8 CMD;
  u8 GROUP;
  u8 NUM_PROPS;
  u8 START_PROP;
  u8 DATA[12];
};

struct cmd_GET_PROPERTY_map {
  u8 CMD;
  u8 GROUP;
  u8 NUM_PROPS;
  u8 START_PROP;
};

struct reply_GET_PROPERTY_map {
  u8 DATA[16];
};

struct cmd_GPIO_PIN_CFG_map {
  u8 CMD;
  u8 GPIO[4];
  u8 NIRQ;
  u8 SDO;
  u8 GEN_CONFIG;
};

struct reply_GPIO_PIN_CFG_map {
  u8 GPIO[4];
  u8 NIRQ;
  u8 SDO;
  u8 GEN_CONFIG;
};

struct cmd_FIFO_INFO_map {
  u8 CMD;
  u8 FIFO;
};

struct reply_FIFO_INFO_map {
  u8 RX_FIFO_COUNT;
  u8 TX_FIFO_SPACE;
};

struct cmd_WAIT_PROPERTY_PROCESSED_map {
  u8 CMD;
};

struct cmd_GET_INT_STATUS_map {
  u8 CMD;
  u8 PH_CLR_PEND;
  u8 MODEM_CLR_PEND;
  u8 CHIP_CLR_PEND;
};

struct reply_GET_INT_STATUS_map {
  u8 INT_PEND;
  u8 INT_STATUS;
  u8 PH_PEND;
  u8 PH_STATUS;
  u8 MODEM_PEND;
  u8 MODEM_STATUS;
  u8 CHIP_PEND;
  u8 CHIP_STATUS;
  u8 INFO_FLAGS;
};

struct cmd_REQUEST_DEVICE_STATE_map {
  u8 CMD;
};

struct reply_REQUEST_DEVICE_STATE_map {
  u8 CURR_STATE;
  u8 CURRENT_CHANNEL;
};

struct cmd_CHANGE_STATE_map {
  u8 CMD;
  u8 NEXT_STATE1;
};

struct cmd_OFFLINE_RECAL_map {
  u8 CMD;
  u8 CAL_CTRL;
  u8 VTR_CAL_ENABLE;
  u8 CAL_ENABLE;
};

struct cmd_READ_CMD_BUFF_map {
  u8 CMD;
};

struct reply_READ_CMD_BUFF_map {
  u8 BYTE[16];
};

struct cmd_FRR_A_READ_map {
  u8 CMD;
};

struct reply_FRR_A_READ_map {
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
};

struct cmd_FRR_B_READ_map {
  u8 CMD;
};

struct reply_FRR_B_READ_map {
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
};

struct cmd_FRR_C_READ_map {
  u8 CMD;
};

struct reply_FRR_C_READ_map {
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
};

struct cmd_FRR_D_READ_map {
  u8 CMD;
};

struct reply_FRR_D_READ_map {
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
};

struct cmd_AGC_OVERRIDE_map {
  u8 CMD;
  u8 AGC_OVERRIDE;
};

struct cmd_IRCAL_map {
  u8 CMD;
  u8 SEARCHING_STEP_SIZE;
  u8 SEARCHING_RSSI_AVG;
  u8 RX_CHAIN_SETTING1;
  u8 RX_CHAIN_SETTING2;
};

struct reply_IRCAL_map {
  u8 CAL_STATE;
  u8 RSSI;
  u8 DIR_CH;
  u8 LAST_RSSI;
};

struct cmd_IRCAL_MANUAL_map {
  u8 CMD;
  u8 IRCAL_AMP;
  u8 IRCAL_PH;
};

struct reply_IRCAL_MANUAL_map {
  u8 IRCAL_AMP_REPLY;
  u8 IRCAL_PH_REPLY;
};

struct cmd_START_TX_map {
  u8 CMD;
  u8 CHANNEL;
  u8 CONDITION;
  u16 TX_LEN;
  u8 TX_DELAY;
  u8 NUM_REPEAT;
};

struct cmd_TX_HOP_map {
  u8 CMD;
  u8 INTE;
  u8 FRAC[3];
  u16 VCO_CNT;
  u16 PLL_SETTLE_TIME;
};

struct cmd_WRITE_TX_FIFO_map {
  u8 CMD;
  u8 DATA[2];
};

struct cmd_PACKET_INFO_map {
  u8 CMD;
  u8 FIELD_NUMBER;
  u16 LEN;
  i16 LEN_DIFF;
};

struct reply_PACKET_INFO_map {
  u16 LENGTH;
};

struct cmd_GET_MODEM_STATUS_map {
  u8 CMD;
  u8 MODEM_CLR_PEND;
};

struct reply_GET_MODEM_STATUS_map {
  u8 MODEM_PEND;
  u8 MODEM_STATUS;
  u8 CURR_RSSI;
  u8 LATCH_RSSI;
  u8 ANT1_RSSI;
  u8 ANT2_RSSI;
  u16 AFC_FREQ_OFFSET;
  u8 INFO_FLAGS;
};

struct cmd_START_RX_map {
  u8 CMD;
  u8 CHANNEL;
  u8 CONDITION;
  u16 RX_LEN;
  u8 NEXT_STATE1;
  u8 NEXT_STATE2;
  u8 NEXT_STATE3;
};

struct cmd_RX_HOP_map {
  u8 CMD;
  u8 INTE;
  u8 FRAC[3];
  u16 VCO_CNT;
};

struct cmd_READ_RX_FIFO_map {
  u8 CMD;
};

struct reply_READ_RX_FIFO_map {
  u8 DATA[2];
};

struct cmd_GET_ADC_READING_map {
  u8 CMD;
  u8 ADC_EN;
  u8 ADC_CFG;
};

struct reply_GET_ADC_READING_map {
  u16 GPIO_ADC;
  u16 BATTERY_ADC;
  u16 TEMP_ADC;
  u8 TEMP_SLOPE;
  u8 TEMP_INTERCEPT;
};

struct cmd_PROTOCOL_CFG_map {
  u8 CMD;
  u8 PROTOCOL;
};

struct cmd_GET_PH_STATUS_map {
  u8 CMD;
  u8 PH_CLR_PEND;
};

struct reply_GET_PH_STATUS_map {
  u8 PH_PEND;
  u8 PH_STATUS;
};

struct cmd_GET_CHIP_STATUS_map {
  u8 CMD;
  u8 CHIP_CLR_PEND;
};

struct reply_GET_CHIP_STATUS_map {
  u8 CHIP_PEND;
  u8 CHIP_STATUS;
  u8 CMD_ERR_STATUS;
  u8 CMD_ERR_CMD_ID;
  u8 INFO_FLAGS;
};

struct cmd_IE154_START_TX_map {
  u8 CMD;
  u8 OPTIONS;
  u8 NETWORK_INDEX;
  u8 NEXT_MODE;
};

struct cmd_IE154_START_RX_map {
  u8 CMD;
  u8 CHANNEL;
  u8 NEXT_MODE;
};

struct cmd_IE154_GET_INT_STATUS_map {
  u8 CMD;
  u8 IE154_TX_CLR_PEND;
  u8 IE154_RX_CLR_PEND;
  u8 IE154_CHIP_CLR_PEND;
};

struct reply_IE154_GET_INT_STATUS_map {
  u8 IE154_INT_PEND;
  u8 IE154_INT_STATUS;
  u8 IE154_TX_PEND;
  u8 IE154_TX_STATUS;
  u8 IE154_RX_PEND;
  u8 IE154_RX_STATUS;
  u8 IE154_CHIP_PEND;
  u8 IE154_CHIP_STATUS;
  u8 IE154_TX_ERR_STATUS;
  u8 IE154_RX_ERR_STATUS;
  u8 TX_FIFO_SPACE;
  u8 RX_FIFO_COUNT;
};

struct cmd_IE154_GET_TX_STATUS_map {
  u8 CMD;
  u8 IE154_TX_CLR_PEND;
};

struct reply_IE154_GET_TX_STATUS_map {
  u8 IE154_TX_PEND;
  u8 IE154_TX_STATUS;
  u8 IE154_TX_ERR_STATUS;
  u8 TX_FIFO_SPACE;
};

struct cmd_IE154_GET_RX_STATUS_map {
  u8 CMD;
  u8 IE154_RX_CLR_PEND;
};

struct reply_IE154_GET_RX_STATUS_map {
  u8 IE154_RX_PEND;
  u8 IE154_RX_STATUS;
  u8 IE154_RX_ERR_STATUS;
  u8 RX_FIFO_COUNT;
  u8 CURRENT_RSSI;
};

struct cmd_IE154_OVERRIDE_NEXT_ACK_map {
  u8 CMD;
  u8 SEQUENCE_NUMBER;
  u8 NEXT;
};

struct reply_IE154_OVERRIDE_NEXT_ACK_map {
  u8 STATUS;
  u8 EXPECTED_SEQUENCE_NUMBER;
};

struct cmd_IE154_GET_MAC_TIMER_map {
  u8 CMD;
};

struct reply_IE154_GET_MAC_TIMER_map {
  u8 MAC_TIMER_VALUE[3];
};

struct cmd_IE154_START_ENERGY_DETECT_map {
  u8 CMD;
  u8 CONFIG;
  u8 CHANNEL;
};

struct cmd_IE154_IS_CHANNEL_CLEAR_map {
  u8 CMD;
  u8 CHANNEL_STATUS;
};

struct cmd_IE154_QUERY_MODE_map {
  u8 CMD;
};

struct reply_IE154_QUERY_MODE_map {
  u16 OPERATING_MODE_PHASE;
  u8 REM_CCA_ATTEMPTS;
};

struct cmd_IE154_START_IDLE_map {
  u8 CMD;
};

struct cmd_IE154_START_SLEEP_map {
  u8 CMD;
};

struct cmd_PEEK_map {
  u8 CMD;
  u16 ADDR[7];
};

struct reply_PEEK_map {
  u8 DATA[7];
};

struct cmd_POKE_map {
  u8 CMD;
  u16 ADDR0;
  u8 DATA0;
  u16 ADDR1;
  u8 DATA1;
  u16 ADDR2;
  u8 DATA2;
  u16 ADDR3;
  u8 DATA3;
  u16 ADDR4;
  u8 DATA4;
};

struct cmd_SRAND_map {
  u8 CMD;
  u32 SEED;
};

struct cmd_DIE_INFO_map {
  u8 CMD;
};

struct reply_DIE_INFO_map {
  u8 DIE_NAME[8];
  u8 ROM_ID;
  u8 CHIP_REV;
};

struct cmd_EZCONFIG_CHECK_map {
  u8 CMD;
  u16 CHECKSUM;
};

struct reply_EZCONFIG_CHECK_map {
  u8 RESULT;
};

struct cmd_EZCONFIG_ARRAY_WRITE_map {
  u8 CMD;
  u8 DATA[2];
};

struct cmd_START_MFSK_map {
  u8 CMD;
  u8 DIR_MODE_CFG;
  u16 FREQ_OFFSET;
};

/* The union that stores the cmd arg read from the host registers */
union cmd_arg_union {
  u8 RAW[16];
  u16 RAW_u16[8];
  i16 RAW_i16[8];
  u32 RAW_u32[4];
  i32 RAW_i32[4];
  struct cmd_GENERIC_map GENERIC;
  struct cmd_POWER_UP_map POWER_UP;
  struct cmd_RAM_TEST_map RAM_TEST;
  struct cmd_PATCH_IMAGE_map PATCH_IMAGE;
  struct cmd_PATCH_ARGS_map PATCH_ARGS;
  struct cmd_PATCH_COPY_map PATCH_COPY;
  struct cmd_TEST_DATA_map TEST_DATA;
  struct cmd_PATCH_COPY_2_map PATCH_COPY_2;
  struct cmd_PATCH_DATA_map PATCH_DATA;
  struct cmd_NOP_map NOP;
  struct cmd_PART_INFO_map PART_INFO;
  struct cmd_FUNC_INFO_map FUNC_INFO;
  struct cmd_SET_PROPERTY_map SET_PROPERTY;
  struct cmd_GET_PROPERTY_map GET_PROPERTY;
  struct cmd_GPIO_PIN_CFG_map GPIO_PIN_CFG;
  struct cmd_FIFO_INFO_map FIFO_INFO;
  struct cmd_WAIT_PROPERTY_PROCESSED_map WAIT_PROPERTY_PROCESSED;
  struct cmd_GET_INT_STATUS_map GET_INT_STATUS;
  struct cmd_REQUEST_DEVICE_STATE_map REQUEST_DEVICE_STATE;
  struct cmd_CHANGE_STATE_map CHANGE_STATE;
  struct cmd_OFFLINE_RECAL_map OFFLINE_RECAL;
  struct cmd_READ_CMD_BUFF_map READ_CMD_BUFF;
  struct cmd_FRR_A_READ_map FRR_A_READ;
  struct cmd_FRR_B_READ_map FRR_B_READ;
  struct cmd_FRR_C_READ_map FRR_C_READ;
  struct cmd_FRR_D_READ_map FRR_D_READ;
  struct cmd_AGC_OVERRIDE_map AGC_OVERRIDE;
  struct cmd_IRCAL_map IRCAL;
  struct cmd_IRCAL_MANUAL_map IRCAL_MANUAL;
  struct cmd_START_TX_map START_TX;
  struct cmd_TX_HOP_map TX_HOP;
  struct cmd_WRITE_TX_FIFO_map WRITE_TX_FIFO;
  struct cmd_PACKET_INFO_map PACKET_INFO;
  struct cmd_GET_MODEM_STATUS_map GET_MODEM_STATUS;
  struct cmd_START_RX_map START_RX;
  struct cmd_RX_HOP_map RX_HOP;
  struct cmd_READ_RX_FIFO_map READ_RX_FIFO;
  struct cmd_GET_ADC_READING_map GET_ADC_READING;
  struct cmd_PROTOCOL_CFG_map PROTOCOL_CFG;
  struct cmd_GET_PH_STATUS_map GET_PH_STATUS;
  struct cmd_GET_CHIP_STATUS_map GET_CHIP_STATUS;
  struct cmd_IE154_START_TX_map IE154_START_TX;
  struct cmd_IE154_START_RX_map IE154_START_RX;
  struct cmd_IE154_GET_INT_STATUS_map IE154_GET_INT_STATUS;
  struct cmd_IE154_GET_TX_STATUS_map IE154_GET_TX_STATUS;
  struct cmd_IE154_GET_RX_STATUS_map IE154_GET_RX_STATUS;
  struct cmd_IE154_OVERRIDE_NEXT_ACK_map IE154_OVERRIDE_NEXT_ACK;
  struct cmd_IE154_GET_MAC_TIMER_map IE154_GET_MAC_TIMER;
  struct cmd_IE154_START_ENERGY_DETECT_map IE154_START_ENERGY_DETECT;
  struct cmd_IE154_IS_CHANNEL_CLEAR_map IE154_IS_CHANNEL_CLEAR;
  struct cmd_IE154_QUERY_MODE_map IE154_QUERY_MODE;
  struct cmd_IE154_START_IDLE_map IE154_START_IDLE;
  struct cmd_IE154_START_SLEEP_map IE154_START_SLEEP;
  struct cmd_PEEK_map PEEK;
  struct cmd_POKE_map POKE;
  struct cmd_SRAND_map SRAND;
  struct cmd_DIE_INFO_map DIE_INFO;
  struct cmd_EZCONFIG_CHECK_map EZCONFIG_CHECK;
  struct cmd_EZCONFIG_ARRAY_WRITE_map EZCONFIG_ARRAY_WRITE;
  struct cmd_START_MFSK_map START_MFSK;
};

/* The union that stores the reply written back to the host registers */
union cmd_reply_union {
  u8 RAW[16];
  struct reply_GENERIC_map GENERIC;
  struct reply_RAM_TEST_map RAM_TEST;
  struct reply_TEST_DATA_map TEST_DATA;
  struct reply_PART_INFO_map PART_INFO;
  struct reply_FUNC_INFO_map FUNC_INFO;
  struct reply_GET_PROPERTY_map GET_PROPERTY;
  struct reply_GPIO_PIN_CFG_map GPIO_PIN_CFG;
  struct reply_FIFO_INFO_map FIFO_INFO;
  struct reply_GET_INT_STATUS_map GET_INT_STATUS;
  struct reply_REQUEST_DEVICE_STATE_map REQUEST_DEVICE_STATE;
  struct reply_READ_CMD_BUFF_map READ_CMD_BUFF;
  struct reply_FRR_A_READ_map FRR_A_READ;
  struct reply_FRR_B_READ_map FRR_B_READ;
  struct reply_FRR_C_READ_map FRR_C_READ;
  struct reply_FRR_D_READ_map FRR_D_READ;
  struct reply_IRCAL_map IRCAL;
  struct reply_IRCAL_MANUAL_map IRCAL_MANUAL;
  struct reply_PACKET_INFO_map PACKET_INFO;
  struct reply_GET_MODEM_STATUS_map GET_MODEM_STATUS;
  struct reply_READ_RX_FIFO_map READ_RX_FIFO;
  struct reply_GET_ADC_READING_map GET_ADC_READING;
  struct reply_GET_PH_STATUS_map GET_PH_STATUS;
  struct reply_GET_CHIP_STATUS_map GET_CHIP_STATUS;
  struct reply_IE154_GET_INT_STATUS_map IE154_GET_INT_STATUS;
  struct reply_IE154_GET_TX_STATUS_map IE154_GET_TX_STATUS;
  struct reply_IE154_GET_RX_STATUS_map IE154_GET_RX_STATUS;
  struct reply_IE154_OVERRIDE_NEXT_ACK_map IE154_OVERRIDE_NEXT_ACK;
  struct reply_IE154_GET_MAC_TIMER_map IE154_GET_MAC_TIMER;
  struct reply_IE154_QUERY_MODE_map IE154_QUERY_MODE;
  struct reply_PEEK_map PEEK;
  struct reply_DIE_INFO_map DIE_INFO;
  struct reply_EZCONFIG_CHECK_map EZCONFIG_CHECK;
};

/* This section contains command buffer declarations */
struct arg_buf_POWER_UP_struct {
  u8 BOOT_OPTIONS;
  u8 XTAL_OPTIONS;
  u32 XO_FREQ;
};

struct arg_buf_RAM_TEST_struct {
  u8 OPERATION;
  u16 CRC_START_ADDR;
  u16 CRC_SIZE;
  u8 RAM_TEST_FILL_BYTE;
};

struct reply_buf_RAM_TEST_struct {
  u8 RESULT;
  u16 OTP_CRC;
  u16 CRC;
};

struct arg_buf_PATCH_IMAGE_struct {
  u8 FLAGS;
  u16 CRC;
  u8 RESERVED1;
  u8 RESERVED2;
  u8 KEY1;
  u8 KEY2;
};

struct arg_buf_PATCH_ARGS_struct {
  u8 PIP;
  u8 RESERVED1;
  u16 ADDR;
  u8 RESERVED2;
  u16 CRC;
};

struct arg_buf_PATCH_COPY_struct {
  u16 SRC_ADDR;
  u16 DST_ADDR;
  u16 COUNT;
};

struct arg_buf_TEST_DATA_struct {
  u8 OFFSET;
};

struct reply_buf_TEST_DATA_struct {
  u8 TEST[16];
};

struct arg_buf_PATCH_COPY_2_struct {
  u16 SRC_ADDR;
  u16 DST_ADDR;
  u16 COUNT;
};

struct arg_buf_PATCH_DATA_struct {
  u8 DATA[8];
};

struct reply_buf_PART_INFO_struct {
  u8 CHIPREV;
  u16 PART;
  u8 PBUILD;
  u16 ID;
  u8 CUSTOMER;
  u8 ROMID;
  u8 BOND;
};

struct reply_buf_FUNC_INFO_struct {
  u8 REVEXT;
  u8 REVBRANCH;
  u8 REVINT;
  u16 PATCH;
  u8 FUNC;
  u8 SVNFLAGS;
  u32 SVNREV;
};

struct arg_buf_SET_PROPERTY_struct {
  u8 GROUP;
  u8 NUM_PROPS;
  u8 START_PROP;
  u8 DATA[12];
};

struct arg_buf_GET_PROPERTY_struct {
  u8 GROUP;
  u8 NUM_PROPS;
  u8 START_PROP;
};

struct reply_buf_GET_PROPERTY_struct {
  u8 DATA[16];
};

struct arg_buf_GPIO_PIN_CFG_struct {
  u8 GPIO[4];
  u8 NIRQ;
  u8 SDO;
  u8 GEN_CONFIG;
};

struct reply_buf_GPIO_PIN_CFG_struct {
  u8 GPIO[4];
  u8 NIRQ;
  u8 SDO;
  u8 GEN_CONFIG;
};

struct arg_buf_FIFO_INFO_struct {
  u8 FIFO;
};

struct reply_buf_FIFO_INFO_struct {
  u8 RX_FIFO_COUNT;
  u8 TX_FIFO_SPACE;
};

struct arg_buf_GET_INT_STATUS_struct {
  u8 PH_CLR_PEND;
  u8 MODEM_CLR_PEND;
  u8 CHIP_CLR_PEND;
};

struct reply_buf_GET_INT_STATUS_struct {
  u8 INT_PEND;
  u8 INT_STATUS;
  u8 PH_PEND;
  u8 PH_STATUS;
  u8 MODEM_PEND;
  u8 MODEM_STATUS;
  u8 CHIP_PEND;
  u8 CHIP_STATUS;
  u8 INFO_FLAGS;
};

struct reply_buf_REQUEST_DEVICE_STATE_struct {
  u8 CURR_STATE;
  u8 CURRENT_CHANNEL;
};

struct arg_buf_CHANGE_STATE_struct {
  u8 NEXT_STATE1;
};

struct arg_buf_OFFLINE_RECAL_struct {
  u8 CAL_CTRL;
  u8 VTR_CAL_ENABLE;
  u8 CAL_ENABLE;
};

struct reply_buf_READ_CMD_BUFF_struct {
  u8 BYTE[16];
};

struct reply_buf_FRR_A_READ_struct {
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
};

struct reply_buf_FRR_B_READ_struct {
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
};

struct reply_buf_FRR_C_READ_struct {
  u8 FRR_C_VALUE;
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
};

struct reply_buf_FRR_D_READ_struct {
  u8 FRR_D_VALUE;
  u8 FRR_A_VALUE;
  u8 FRR_B_VALUE;
  u8 FRR_C_VALUE;
};

struct arg_buf_AGC_OVERRIDE_struct {
  u8 AGC_OVERRIDE;
};

struct arg_buf_IRCAL_struct {
  u8 SEARCHING_STEP_SIZE;
  u8 SEARCHING_RSSI_AVG;
  u8 RX_CHAIN_SETTING1;
  u8 RX_CHAIN_SETTING2;
};

struct reply_buf_IRCAL_struct {
  u8 CAL_STATE;
  u8 RSSI;
  u8 DIR_CH;
  u8 LAST_RSSI;
};

struct arg_buf_IRCAL_MANUAL_struct {
  u8 IRCAL_AMP;
  u8 IRCAL_PH;
};

struct reply_buf_IRCAL_MANUAL_struct {
  u8 IRCAL_AMP_REPLY;
  u8 IRCAL_PH_REPLY;
};

struct arg_buf_START_TX_struct {
  u8 CHANNEL;
  u8 CONDITION;
  u16 TX_LEN;
  u8 TX_DELAY;
  u8 NUM_REPEAT;
};

struct arg_buf_TX_HOP_struct {
  u8 INTE;
  u8 FRAC[3];
  u16 VCO_CNT;
  u16 PLL_SETTLE_TIME;
};

struct arg_buf_WRITE_TX_FIFO_struct {
  u8 DATA[2];
};

struct arg_buf_PACKET_INFO_struct {
  u8 FIELD_NUMBER;
  u16 LEN;
  i16 LEN_DIFF;
};

struct reply_buf_PACKET_INFO_struct {
  u16 LENGTH;
};

struct arg_buf_GET_MODEM_STATUS_struct {
  u8 MODEM_CLR_PEND;
};

struct reply_buf_GET_MODEM_STATUS_struct {
  u8 MODEM_PEND;
  u8 MODEM_STATUS;
  u8 CURR_RSSI;
  u8 LATCH_RSSI;
  u8 ANT1_RSSI;
  u8 ANT2_RSSI;
  u16 AFC_FREQ_OFFSET;
  u8 INFO_FLAGS;
};

struct arg_buf_START_RX_struct {
  u8 CHANNEL;
  u8 CONDITION;
  u16 RX_LEN;
  u8 NEXT_STATE1;
  u8 NEXT_STATE2;
  u8 NEXT_STATE3;
};

struct arg_buf_RX_HOP_struct {
  u8 INTE;
  u8 FRAC[3];
  u16 VCO_CNT;
};

struct reply_buf_READ_RX_FIFO_struct {
  u8 DATA[2];
};

struct arg_buf_GET_ADC_READING_struct {
  u8 ADC_EN;
  u8 ADC_CFG;
};

struct reply_buf_GET_ADC_READING_struct {
  u16 GPIO_ADC;
  u16 BATTERY_ADC;
  u16 TEMP_ADC;
  u8 TEMP_SLOPE;
  u8 TEMP_INTERCEPT;
};

struct arg_buf_PROTOCOL_CFG_struct {
  u8 PROTOCOL;
};

struct arg_buf_GET_PH_STATUS_struct {
  u8 PH_CLR_PEND;
};

struct reply_buf_GET_PH_STATUS_struct {
  u8 PH_PEND;
  u8 PH_STATUS;
};

struct arg_buf_GET_CHIP_STATUS_struct {
  u8 CHIP_CLR_PEND;
};

struct reply_buf_GET_CHIP_STATUS_struct {
  u8 CHIP_PEND;
  u8 CHIP_STATUS;
  u8 CMD_ERR_STATUS;
  u8 CMD_ERR_CMD_ID;
  u8 INFO_FLAGS;
};

struct arg_buf_IE154_START_TX_struct {
  u8 OPTIONS;
  u8 NETWORK_INDEX;
  u8 NEXT_MODE;
};

struct arg_buf_IE154_START_RX_struct {
  u8 CHANNEL;
  u8 NEXT_MODE;
};

struct arg_buf_IE154_GET_INT_STATUS_struct {
  u8 IE154_TX_CLR_PEND;
  u8 IE154_RX_CLR_PEND;
  u8 IE154_CHIP_CLR_PEND;
};

struct reply_buf_IE154_GET_INT_STATUS_struct {
  u8 IE154_INT_PEND;
  u8 IE154_INT_STATUS;
  u8 IE154_TX_PEND;
  u8 IE154_TX_STATUS;
  u8 IE154_RX_PEND;
  u8 IE154_RX_STATUS;
  u8 IE154_CHIP_PEND;
  u8 IE154_CHIP_STATUS;
  u8 IE154_TX_ERR_STATUS;
  u8 IE154_RX_ERR_STATUS;
  u8 TX_FIFO_SPACE;
  u8 RX_FIFO_COUNT;
};

struct arg_buf_IE154_GET_TX_STATUS_struct {
  u8 IE154_TX_CLR_PEND;
};

struct reply_buf_IE154_GET_TX_STATUS_struct {
  u8 IE154_TX_PEND;
  u8 IE154_TX_STATUS;
  u8 IE154_TX_ERR_STATUS;
  u8 TX_FIFO_SPACE;
};

struct arg_buf_IE154_GET_RX_STATUS_struct {
  u8 IE154_RX_CLR_PEND;
};

struct reply_buf_IE154_GET_RX_STATUS_struct {
  u8 IE154_RX_PEND;
  u8 IE154_RX_STATUS;
  u8 IE154_RX_ERR_STATUS;
  u8 RX_FIFO_COUNT;
  u8 CURRENT_RSSI;
};

struct arg_buf_IE154_OVERRIDE_NEXT_ACK_struct {
  u8 SEQUENCE_NUMBER;
  u8 NEXT;
};

struct reply_buf_IE154_OVERRIDE_NEXT_ACK_struct {
  u8 STATUS;
  u8 EXPECTED_SEQUENCE_NUMBER;
};

struct reply_buf_IE154_GET_MAC_TIMER_struct {
  u8 MAC_TIMER_VALUE[3];
};

struct arg_buf_IE154_START_ENERGY_DETECT_struct {
  u8 CONFIG;
  u8 CHANNEL;
};

struct arg_buf_IE154_IS_CHANNEL_CLEAR_struct {
  u8 CHANNEL_STATUS;
};

struct reply_buf_IE154_QUERY_MODE_struct {
  u16 OPERATING_MODE_PHASE;
  u8 REM_CCA_ATTEMPTS;
};

struct arg_buf_PEEK_struct {
  u16 ADDR[7];
};

struct reply_buf_PEEK_struct {
  u8 DATA[7];
};

struct arg_buf_POKE_struct {
  u16 ADDR0;
  u8 DATA0;
  u16 ADDR1;
  u8 DATA1;
  u16 ADDR2;
  u8 DATA2;
  u16 ADDR3;
  u8 DATA3;
  u16 ADDR4;
  u8 DATA4;
};

struct arg_buf_SRAND_struct {
  u32 SEED;
};

struct reply_buf_DIE_INFO_struct {
  u8 DIE_NAME[8];
  u8 ROM_ID;
  u8 CHIP_REV;
};

struct arg_buf_EZCONFIG_CHECK_struct {
  u16 CHECKSUM;
};

struct reply_buf_EZCONFIG_CHECK_struct {
  u8 RESULT;
};

struct arg_buf_EZCONFIG_ARRAY_WRITE_struct {
  u8 DATA[2];
};

struct arg_buf_START_MFSK_struct {
  u8 DIR_MODE_CFG;
  u16 FREQ_OFFSET;
};

/* This section is a place holder for all command isr handlers */
extern void cmd_isr_dispatch(void);
extern void cmd_isr_power_up(void);
extern void cmd_isr_ram_test(void);
extern void cmd_isr_patch_image(void);
extern void cmd_isr_patch_args(void);
extern void cmd_isr_patch_copy(void);
extern void cmd_isr_test_data(void);
extern void cmd_isr_patch_copy_2(void);
extern void cmd_isr_patch_data(void);
extern void cmd_isr_nop(void);
extern void cmd_isr_part_info(void);
extern void cmd_isr_func_info(void);
extern void cmd_isr_set_property(void);
extern void cmd_isr_get_property(void);
extern void cmd_isr_gpio_pin_cfg(void);
extern void cmd_isr_fifo_info(void);
extern void cmd_isr_wait_property_processed(void);
extern void cmd_isr_get_int_status(void);
extern void cmd_isr_request_device_state(void);
extern void cmd_isr_change_state(void);
extern void cmd_isr_offline_recal(void);
extern void cmd_isr_read_cmd_buff(void);
extern void cmd_isr_frr_a_read(void);
extern void cmd_isr_frr_b_read(void);
extern void cmd_isr_frr_c_read(void);
extern void cmd_isr_frr_d_read(void);
extern void cmd_isr_agc_override(void);
extern void cmd_isr_ircal(void);
extern void cmd_isr_ircal_manual(void);
extern void cmd_isr_start_tx(void);
extern void cmd_isr_tx_hop(void);
extern void cmd_isr_write_tx_fifo(void);
extern void cmd_isr_packet_info(void);
extern void cmd_isr_get_modem_status(void);
extern void cmd_isr_start_rx(void);
extern void cmd_isr_rx_hop(void);
extern void cmd_isr_read_rx_fifo(void);
extern void cmd_isr_get_adc_reading(void);
extern void cmd_isr_protocol_cfg(void);
extern void cmd_isr_get_ph_status(void);
extern void cmd_isr_get_chip_status(void);
extern void cmd_isr_ie154_start_tx(void);
extern void cmd_isr_ie154_start_rx(void);
extern void cmd_isr_ie154_get_int_status(void);
extern void cmd_isr_ie154_get_tx_status(void);
extern void cmd_isr_ie154_get_rx_status(void);
extern void cmd_isr_ie154_override_next_ack(void);
extern void cmd_isr_ie154_get_mac_timer(void);
extern void cmd_isr_ie154_start_energy_detect(void);
extern void cmd_isr_ie154_is_channel_clear(void);
extern void cmd_isr_ie154_query_mode(void);
extern void cmd_isr_ie154_start_idle(void);
extern void cmd_isr_ie154_start_sleep(void);
extern void cmd_isr_peek(void);
extern void cmd_isr_poke(void);
extern void cmd_isr_srand(void);
extern void cmd_isr_die_info(void);
extern void cmd_isr_ezconfig_check(void);
extern void cmd_isr_ezconfig_array_write(void);
extern void cmd_isr_start_mfsk(void);

/* This section defines command id as command value */
#define cmd_ID_POWER_UP                         0x02
#define cmd_ID_RAM_TEST                         0x03
#define cmd_ID_PATCH_IMAGE                      0x04
#define cmd_ID_PATCH_ARGS                       0x05
#define cmd_ID_PATCH_COPY                       0x06
#define cmd_ID_TEST_DATA                        0x09
#define cmd_ID_PATCH_COPY_2                     0x0a
#define cmd_ID_PATCH_DATA                       0xe0
#define cmd_ID_NOP                              0x00
#define cmd_ID_PART_INFO                        0x01
#define cmd_ID_FUNC_INFO                        0x10
#define cmd_ID_SET_PROPERTY                     0x11
#define cmd_ID_GET_PROPERTY                     0x12
#define cmd_ID_GPIO_PIN_CFG                     0x13
#define cmd_ID_FIFO_INFO                        0x15
#define cmd_ID_WAIT_PROPERTY_PROCESSED          0x1b
#define cmd_ID_GET_INT_STATUS                   0x20
#define cmd_ID_REQUEST_DEVICE_STATE             0x33
#define cmd_ID_CHANGE_STATE                     0x34
#define cmd_ID_OFFLINE_RECAL                    0x38
#define cmd_ID_READ_CMD_BUFF                    0x44
#define cmd_ID_FRR_A_READ                       0x50
#define cmd_ID_FRR_B_READ                       0x51
#define cmd_ID_FRR_C_READ                       0x53
#define cmd_ID_FRR_D_READ                       0x57
#define cmd_ID_AGC_OVERRIDE                     0xd0
#define cmd_ID_IRCAL                            0x17
#define cmd_ID_IRCAL_MANUAL                     0x1a
#define cmd_ID_START_TX                         0x31
#define cmd_ID_TX_HOP                           0x37
#define cmd_ID_WRITE_TX_FIFO                    0x66
#define cmd_ID_PACKET_INFO                      0x16
#define cmd_ID_GET_MODEM_STATUS                 0x22
#define cmd_ID_START_RX                         0x32
#define cmd_ID_RX_HOP                           0x36
#define cmd_ID_READ_RX_FIFO                     0x77
#define cmd_ID_GET_ADC_READING                  0x14
#define cmd_ID_PROTOCOL_CFG                     0x18
#define cmd_ID_GET_PH_STATUS                    0x21
#define cmd_ID_GET_CHIP_STATUS                  0x23
#define cmd_ID_IE154_START_TX                   0x80
#define cmd_ID_IE154_START_RX                   0x81
#define cmd_ID_IE154_GET_INT_STATUS             0x82
#define cmd_ID_IE154_GET_TX_STATUS              0x83
#define cmd_ID_IE154_GET_RX_STATUS              0x84
#define cmd_ID_IE154_OVERRIDE_NEXT_ACK          0x85
#define cmd_ID_IE154_GET_MAC_TIMER              0x86
#define cmd_ID_IE154_START_ENERGY_DETECT        0x87
#define cmd_ID_IE154_IS_CHANNEL_CLEAR           0x89
#define cmd_ID_IE154_QUERY_MODE                 0x8a
#define cmd_ID_IE154_START_IDLE                 0x8c
#define cmd_ID_IE154_START_SLEEP                0x8d
#define cmd_ID_PEEK                             0xf0
#define cmd_ID_POKE                             0xf1
#define cmd_ID_SRAND                            0xf2
#define cmd_ID_DIE_INFO                         0xfe
#define cmd_ID_EZCONFIG_CHECK                   0x19
#define cmd_ID_EZCONFIG_ARRAY_WRITE             0x66
#define cmd_ID_START_MFSK                       0x35

#endif /* _CMD_MAP_H_ */
