/*
 * Silicon Laboratories Confidential
 * Copyright 2008-2013 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#ifndef _PROP_MAP_H_
#define _PROP_MAP_H_

struct prop_map_struct {
  u8 prop_grp_id;
  u8 prop_grp_len;
  u8 xdata * prop_grp_start_addr;
};
extern struct prop_map_struct code prop_map[];
extern xdata u8 code * prop_map_start_ptr;

/* The property group id defines */
#define PROP_GRP_ID_GLOBAL 0
#define PROP_GRP_ID_INT_CTL 1
#define PROP_GRP_ID_FRR_CTL 2
#define PROP_GRP_ID_PREAMBLE 16
#define PROP_GRP_ID_SYNC 17
#define PROP_GRP_ID_PKT 18
#define PROP_GRP_ID_MODEM 32
#define PROP_GRP_ID_MODEM_CHFLT 33
#define PROP_GRP_ID_PA 34
#define PROP_GRP_ID_SYNTH 35
#define PROP_GRP_ID_EZCONFIG 36
#define PROP_GRP_ID_MATCH 48
#define PROP_GRP_ID_FREQ_CONTROL 64
#define PROP_GRP_ID_RX_HOP 80
#define PROP_GRP_ID_IE154_TX 96
#define PROP_GRP_ID_IE154_RX 97
#define PROP_GRP_ID_IE154_COMMON 98
#define PROP_GRP_ID_IE154_INT_CTL 99
#define PROP_GRP_ID_IE154_NETWORK 100
#define PROP_GRP_ID_MBUS 112
#define PROP_GRP_ID_PTI 240
#define PROP_GRP_ID_OTP_VARS 242

/* The property group index must match index in arrays below */
#define PROP_GRP_INDEX_FRR_CTL 0
#define PROP_GRP_INDEX_GLOBAL 1
#define PROP_GRP_INDEX_FREQ_CONTROL 2
#define PROP_GRP_INDEX_PREAMBLE 3
#define PROP_GRP_INDEX_SYNC 4
#define PROP_GRP_INDEX_PKT 5
#define PROP_GRP_INDEX_MODEM 6
#define PROP_GRP_INDEX_MODEM_CHFLT 7
#define PROP_GRP_INDEX_PA 8
#define PROP_GRP_INDEX_SYNTH 9
#define PROP_GRP_INDEX_MISC_DEBUG 10
#define PROP_GRP_INDEX_IE154_INT_CTL 11
#define PROP_GRP_INDEX_INT_CTL 11
#define PROP_GRP_INDEX_IE154_TX 12
#define PROP_GRP_INDEX_MATCH 12
#define PROP_GRP_INDEX_MBUS 12
#define PROP_GRP_INDEX_EZCONFIG 13
#define PROP_GRP_INDEX_IE154_RX 13
#define PROP_GRP_INDEX_IE154_COMMON 14
#define PROP_GRP_INDEX_RX_HOP 14
#define PROP_GRP_INDEX_PTI 15
#define PROP_GRP_INDEX_IE154_NETWORK 16

/* Number of property group defines */
#define PROPERTY_TOTAL_NUM_GROUPS 22
#define PROPERTY_NUM_GROUPS 17
#define PROPERTY_GROUP_MASK ((1 << PROPERTY_NUM_GROUPS) - 1)

/* The property group length defines */
#define PROP_GRP_LEN_GLOBAL 11
#define PROP_GRP_LEN_INT_CTL 4
#define PROP_GRP_LEN_FRR_CTL 4
#define PROP_GRP_LEN_PREAMBLE 15
#define PROP_GRP_LEN_SYNC 10
#define PROP_GRP_LEN_PKT 58
#define PROP_GRP_LEN_MODEM 96
#define PROP_GRP_LEN_MODEM_CHFLT 36
#define PROP_GRP_LEN_PA 7
#define PROP_GRP_LEN_SYNTH 8
#define PROP_GRP_LEN_EZCONFIG 9
#define PROP_GRP_LEN_MATCH 12
#define PROP_GRP_LEN_FREQ_CONTROL 8
#define PROP_GRP_LEN_RX_HOP 66
#define PROP_GRP_LEN_IE154_TX 23
#define PROP_GRP_LEN_IE154_RX 11
#define PROP_GRP_LEN_IE154_COMMON 7
#define PROP_GRP_LEN_IE154_INT_CTL 4
#define PROP_GRP_LEN_IE154_NETWORK 25
#define PROP_GRP_LEN_MBUS 1
#define PROP_GRP_LEN_PTI 5
#define PROP_GRP_LEN_OTP_VARS 55

/* The global declarations of all properties */
struct prop_grp_global_struct {
  u8 xo_tune;
  u8 clk_cfg;
  u8 low_batt_thresh;
  u8 config;
  u8 wut_config;
  u8 wut_m[2];
  u8 wut_r;
  u8 wut_ldc;
  u8 wut_cal;
  u8 bufclk_cfg;
};

struct prop_grp_int_ctl_struct {
  u8 enable;
  u8 ph_enable;
  u8 modem_enable;
  u8 chip_enable;
};

struct prop_grp_frr_ctl_struct {
  u8 a_mode;
  u8 b_mode;
  u8 c_mode;
  u8 d_mode;
};

struct prop_grp_preamble_struct {
  u8 tx_length;
  u8 config_std_1;
  u8 config_nstd;
  u8 config_std_2;
  u8 config;
  u8 pattern[4];
  u8 postamble_config;
  u8 postamble_pattern[4];
  u8 reserved_10_0e;
};

struct prop_grp_sync_struct {
  u8 config;
  u8 bits[4];
  u8 config2;
  u8 bits2[4];
};

struct prop_grp_pkt_struct {
  u8 crc_config;
  u8 wht_poly[2];
  u8 wht_seed[2];
  u8 wht_bit_num;
  u8 config1;
  u8 config2;
  u8 len;
  u8 len_field_source;
  u8 len_adjust;
  u8 tx_threshold;
  u8 rx_threshold;
  u8 field_1_length[2];
  u8 field_1_config;
  u8 field_1_crc_config;
  u8 field_2_length[2];
  u8 field_2_config;
  u8 field_2_crc_config;
  u8 field_3_length[2];
  u8 field_3_config;
  u8 field_3_crc_config;
  u8 field_4_length[2];
  u8 field_4_config;
  u8 field_4_crc_config;
  u8 field_5_length[2];
  u8 field_5_config;
  u8 field_5_crc_config;
  u8 rx_field_1_length[2];
  u8 rx_field_1_config;
  u8 rx_field_1_crc_config;
  u8 rx_field_2_length[2];
  u8 rx_field_2_config;
  u8 rx_field_2_crc_config;
  u8 rx_field_3_length[2];
  u8 rx_field_3_config;
  u8 rx_field_3_crc_config;
  u8 rx_field_4_length[2];
  u8 rx_field_4_config;
  u8 rx_field_4_crc_config;
  u8 rx_field_5_length[2];
  u8 rx_field_5_config;
  u8 rx_field_5_crc_config;
  u8 repeat;
  u8 crc_seed[4];
};

struct prop_grp_modem_struct {
  u8 mod_type;
  u8 map_control;
  u8 dsm_ctrl;
  u8 data_rate[3];
  u8 tx_nco_mode[4];
  u8 freq_dev[3];
  u8 freq_offset[2];
  u8 tx_filter_coeff_8;
  u8 tx_filter_coeff_7;
  u8 tx_filter_coeff_6;
  u8 tx_filter_coeff_5;
  u8 tx_filter_coeff_4;
  u8 tx_filter_coeff_3;
  u8 tx_filter_coeff_2;
  u8 tx_filter_coeff_1;
  u8 tx_filter_coeff_0;
  u8 tx_ramp_delay;
  u8 mdm_ctrl;
  u8 if_control;
  u8 if_freq[3];
  u8 decimation_cfg1;
  u8 decimation_cfg0;
  u8 decimation_cfg2;
  u8 ifpkd_thresholds;
  u8 bcr_osr[2];
  u8 bcr_nco_offset[3];
  u8 bcr_gain[2];
  u8 bcr_gear;
  u8 bcr_misc1;
  u8 bcr_misc0;
  u8 afc_gear;
  u8 afc_wait;
  u8 afc_gain[2];
  u8 afc_limiter[2];
  u8 afc_misc;
  u8 afc_zifoff;
  u8 adc_ctrl;
  u8 agc_control;
  u8 reserved_20_36;
  u8 reserved_20_37;
  u8 agc_window_size;
  u8 agc_rfpd_decay;
  u8 agc_ifpd_decay;
  u8 fsk4_gain1;
  u8 fsk4_gain0;
  u8 fsk4_th[2];
  u8 fsk4_map;
  u8 ook_pdtc;
  u8 ook_blopk;
  u8 ook_cnt1;
  u8 ook_misc;
  u8 raw_search;
  u8 raw_control;
  u8 raw_eye[2];
  u8 ant_div_mode;
  u8 ant_div_control;
  u8 rssi_thresh;
  u8 rssi_jump_thresh;
  u8 rssi_control;
  u8 rssi_control2;
  u8 rssi_comp;
  u8 dc_control;
  u8 raw_search2;
  u8 clkgen_band;
  u8 reserved_20_52;
  u8 pll_settle_time;
  u8 spike_det;
  u8 one_shot_afc;
  u8 rssi_hysteresis;
  u8 rssi_mute;
  u8 fast_rssi_delay;
  u8 psm[2];
  u8 dsa_ctrl1;
  u8 dsa_ctrl2;
  u8 dsa_qual;
  u8 dsa_rssi;
  u8 dsa_misc;
};

struct prop_grp_modem_chflt_struct {
  u8 rx1_chflt_coe[18];
  u8 rx2_chflt_coe[18];
};

struct prop_grp_pa_struct {
  u8 mode;
  u8 pwr_lvl;
  u8 bias_clkduty;
  u8 tc;
  u8 ramp_ex;
  u8 ramp_down_delay;
  u8 dig_pwr_seq_config;
};

struct prop_grp_synth_struct {
  u8 pfdcp_cpff;
  u8 pfdcp_cpint;
  u8 vco_kv;
  u8 lpfilt3;
  u8 lpfilt2;
  u8 lpfilt1;
  u8 lpfilt0;
  u8 vco_kvcal;
};

struct prop_grp_ezconfig_struct {
  u8 modulation;
  u8 config_select;
  u8 pkt;
  u8 xo_tune;
  u8 spare0;
  u8 spare1;
  u8 spare2;
  u8 spare3;
  u8 spare4;
};

struct prop_grp_match_struct {
  u8 value_1;
  u8 mask_1;
  u8 ctrl_1;
  u8 value_2;
  u8 mask_2;
  u8 ctrl_2;
  u8 value_3;
  u8 mask_3;
  u8 ctrl_3;
  u8 value_4;
  u8 mask_4;
  u8 ctrl_4;
};

struct prop_grp_freq_control_struct {
  u8 inte;
  u8 frac[3];
  u8 channel_step_size[2];
  u8 w_size;
  u8 vcocnt_rx_adj;
};

struct prop_grp_rx_hop_struct {
  u8 control;
  u8 table_size;
  u8 table_entry[64];
};

struct prop_grp_ie154_tx_struct {
  u8 flags;
  u8 backoff_turnaround_time_symbols;
  u8 ack_timeout[2];
  u8 cca_mode;
  u8 cca_threshold;
  u8 csma_backoff_base_symbols[2];
  u8 csma_backoff[10];
  u8 csma_on_symbols[2];
  u8 lbt_clear_time_min;
  u8 lbt_clear_time_max;
  u8 lbt_total_time;
};

struct prop_grp_ie154_rx_struct {
  u8 flags;
  u8 flags2;
  u8 backoff_turnaround_time;
  u8 eui_64[8];
};

struct prop_grp_ie154_common_struct {
  u8 flags;
  u8 phy_cfg;
  u8 max_payload_size[2];
  u8 min_payload_size;
  u8 xtal_tick_per_symbol[2];
};

struct prop_grp_ie154_int_ctl_struct {
  u8 enable;
  u8 tx_enable;
  u8 rx_enable;
  u8 ie154_chip_enable;
};

struct prop_grp_ie154_network_struct {
  u8 coordinator_mask;
  u8 list[4][6];
};

struct prop_grp_mbus_struct {
  u8 frame;
};

struct prop_grp_pti_struct {
  u8 ctl;
  u8 baud[2];
  u8 log_en;
  u8 log_en_2;
};

struct prop_grp_otp_vars_struct {
  u8 spi_active_seq_delay[2];
  u8 tx_tune_seq_delay;
  u8 ready_seq_delay;
  u8 rx_seq_delay[2];
  u8 cal_enable_vtr;
  u8 cal_enable;
  u8 vtr_vco_v3p3_target_voltage;
  u8 vtr_vco_v1p5_target_voltage;
  u8 vtr_vco_ladr_target_voltage;
  u8 rc_cal_adc_target[2];
  u8 rc_cal;
  u8 rc_cal1;
  u8 rc_cal2;
  u8 boot_osc_cal;
  u8 boot_osc_cal1;
  u8 auxadc_temp_slope;
  u8 auxadc_temp_intercept;
  u8 auxadc_sy_gain_error;
  u8 auxadc_sy_offset_error;
  u8 adc_voltage_trim;
  u8 vco_load5_xo;
  u8 reg_rxfe_lpf;
  u8 reg_adc_lpf;
  u8 reg_clkgen_com_lpf;
  u8 reg_fbdiv_lpf;
  u8 reg_clkgen_tx_lpf;
  u8 reg_clkgen_com_low_band;
  u8 reg_rxfe_hpf;
  u8 reg_adc_hpf;
  u8 reg_clkgen_com_hpf;
  u8 reg_fbdiv_hpf;
  u8 reg_clkgen_tx_hpf;
  u8 etsi_cfg0;
  u8 etsi_cfg1;
  u8 etsi_cfg2;
  u8 ph_watermark;
  u8 proc_mon_rcal;
  u8 ref_cal_bandgap;
  u8 vco_adj;
  u8 misc_delay;
  u8 cal_man;
  u8 reg_clkgen_com_hpf_hot;
  u8 vtr_vco_v1p5_target_voltage_hot;
  u8 reg_fbdiv_com_hot;
  u8 reg_dig_load_acfg_digreg_hot;
  u8 cal_man_offline_temp_delta;
  u8 cal_man_offline2_temp_delta;
  u8 cal_man_offline_cal_vtr;
  u8 cal_man_offline_cal;
  u8 nvm_timing;
  u8 spare_35;
  u8 spare_36;
};

/* The group declarations of all prop structures */
extern struct prop_grp_global_struct xdata prop_global;
extern struct prop_grp_int_ctl_struct xdata prop_int_ctl;
extern struct prop_grp_frr_ctl_struct xdata prop_frr_ctl;
extern struct prop_grp_preamble_struct xdata prop_preamble;
extern struct prop_grp_sync_struct xdata prop_sync;
extern struct prop_grp_pkt_struct xdata prop_pkt;
extern struct prop_grp_modem_struct xdata prop_modem;
extern struct prop_grp_modem_chflt_struct xdata prop_modem_chflt;
extern struct prop_grp_pa_struct xdata prop_pa;
extern struct prop_grp_synth_struct xdata prop_synth;
extern struct prop_grp_ezconfig_struct xdata prop_ezconfig;
extern struct prop_grp_match_struct xdata prop_match;
extern struct prop_grp_freq_control_struct xdata prop_freq_control;
extern struct prop_grp_rx_hop_struct xdata prop_rx_hop;
extern struct prop_grp_ie154_tx_struct xdata prop_ie154_tx;
extern struct prop_grp_ie154_rx_struct xdata prop_ie154_rx;
extern struct prop_grp_ie154_common_struct xdata prop_ie154_common;
extern struct prop_grp_ie154_int_ctl_struct xdata prop_ie154_int_ctl;
extern struct prop_grp_ie154_network_struct xdata prop_ie154_network;
extern struct prop_grp_mbus_struct xdata prop_mbus;
extern struct prop_grp_pti_struct xdata prop_pti;
extern struct prop_grp_otp_vars_struct xdata prop_otp_vars;

/* This section is a place holder for all property handlers */
extern void property_grp_cb_global(void);
extern void property_grp_cb_int_ctl(void);
extern void property_grp_cb_frr_ctl(void);
extern void property_grp_cb_preamble(void);
extern void property_grp_cb_sync(void);
extern void property_grp_cb_pkt(void);
extern void property_grp_cb_modem(void);
extern void property_grp_cb_modem_chflt(void);
extern void property_grp_cb_pa(void);
extern void property_grp_cb_synth(void);
extern void property_grp_cb_ezconfig(void);
extern void property_grp_cb_match(void);
extern void property_grp_cb_freq_control(void);
extern void property_grp_cb_rx_hop(void);
extern void property_grp_cb_ie154_tx(void);
extern void property_grp_cb_ie154_rx(void);
extern void property_grp_cb_ie154_common(void);
extern void property_grp_cb_ie154_int_ctl(void);
extern void property_grp_cb_ie154_network(void);
extern void property_grp_cb_mbus(void);
extern void property_grp_cb_pti(void);
extern void property_grp_cb_otp_vars(void);

#endif /* _PROP_MAP_H_ */
