/***************************************************************************//**
 * @file
 * @brief Krakatoa Indirect Register Definitions
 *
 * Please Note: This file is automatically generated, and should not
 *       be directly edited, please modify the template or reg spec instead
 *
 * Generated by reg_spec.pl, Revision: 1.13
 *   on Wed Nov 28 19:22:49 2007
 *   from krakatoaIndirectAnalogue.spec, Revision:
 *   using template xap2b-indirect-h.template, Revision: #8
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
#ifndef __KRAKATOA_INDIRECT_REGS_H__
#define __KRAKATOA_INDIRECT_REGS_H__  1

#ifndef KRAKATOA_INDIRECT_SPEC_REV
#define KRAKATOA_INDIRECT_SPEC_REV
#endif//KRAKATOA_INDIRECT_SPEC_REV

/*****************************************************************************
* ---- ANALOGUE_CONTROL -- Analogue RF Control ----
* 0x0000 - 0x00FF
*   control and status registers for the analog section of the chip.
*****************************************************************************/
#define DATA_ANALOGUE_CONTROL_BASE    (0x0000u)
#define DATA_ANALOGUE_CONTROL_END     (0x00FFu)
#define DATA_ANALOGUE_CONTROL_TOP     ((DATA_ANALOGUE_CONTROL_END | 1) + 1)
#define DATA_ANALOGUE_CONTROL_SIZE    (DATA_ANALOGUE_CONTROL_TOP - DATA_ANALOGUE_CONTROL_BASE)

/** IFFILTER_H - RW - IF filter serial register **/
#define IFFILTER_H_REG                (0x0010u)
// Pre filter tune value - RW [0:4]
# define IFFILTER_H_TUNE_PRE_FILTER_MASK          (0x001Fu)
# define IFFILTER_H_TUNE_PRE_FILTER_BIT           (0)
# define IFFILTER_H_TUNE_PRE_FILTER_BITS          (5)
// Channel filter tune value - RW [5:9]
# define IFFILTER_H_TUNE_CH_FILTER_MASK           (0x03E0u)
# define IFFILTER_H_TUNE_CH_FILTER_BIT            (5)
# define IFFILTER_H_TUNE_CH_FILTER_BITS           (5)
// IQ trim - RW [10:15]
# define IFFILTER_H_IQ_TRIM_MASK                  (0xFC00u)
# define IFFILTER_H_IQ_TRIM_BIT                   (10)
# define IFFILTER_H_IQ_TRIM_BITS                  (6)

/** IFFILTER_L - RW - IF filter serial register **/
#define IFFILTER_L_REG                (0x0011u)
// channel filter current reference trim - RW [0:5]
# define IFFILTER_L_BIAS_FILTERI_MASK             (0x003Fu)
# define IFFILTER_L_BIAS_FILTERI_BIT              (0)
# define IFFILTER_L_BIAS_FILTERI_BITS             (6)
// channel filter voltage reference trim - RW [6:11]
# define IFFILTER_L_BIAS_FILTERV_MASK             (0x0FC0u)
# define IFFILTER_L_BIAS_FILTERV_BIT              (6)
# define IFFILTER_L_BIAS_FILTERV_BITS             (6)
// channel filter complex mode (1=complex) - RW [12:12]
# define IFFILTER_L_CH_FILTER_COMPLEX_EN_B_MASK   (0x1000u)
# define IFFILTER_L_CH_FILTER_COMPLEX_EN_B_BIT    (12)
# define IFFILTER_L_CH_FILTER_COMPLEX_EN_B_BITS   (1)
// mixer phase switch - RW [13:13]
# define IFFILTER_L_MIXER_PHASE_SW_MASK           (0x2000u)
# define IFFILTER_L_MIXER_PHASE_SW_BIT            (13)
# define IFFILTER_L_MIXER_PHASE_SW_BITS           (1)
// Not used - RW [14:15]
# define IFFILTER_L_UNUSED_MASK                   (0xC000u)
# define IFFILTER_L_UNUSED_BIT                    (14)
# define IFFILTER_L_UNUSED_BITS                   (2)

/** LNA_L - RW - LNA serial regsiter **/
#define LNA_L_REG                     (0x0020u)
// lna tune value - RW [0:5]
# define LNA_L_TUNE_LNA_MASK                      (0x003Fu)
# define LNA_L_TUNE_LNA_BIT                       (0)
# define LNA_L_TUNE_LNA_BITS                      (6)
// lna gain trim - RW [6:7]
# define LNA_L_LNA_GAIN_TRIM_MASK                 (0x00C0u)
# define LNA_L_LNA_GAIN_TRIM_BIT                  (6)
# define LNA_L_LNA_GAIN_TRIM_BITS                 (2)
// lna voltage reference trim - RW [8:13]
# define LNA_L_BIAS_LNAV_MASK                     (0x3F00u)
# define LNA_L_BIAS_LNAV_BIT                      (8)
# define LNA_L_BIAS_LNAV_BITS                     (6)
// Not used - RW [14:15]
# define LNA_L_UNUSED_MASK                        (0xC000u)
# define LNA_L_UNUSED_BIT                         (14)
# define LNA_L_UNUSED_BITS                        (2)

/** IFAMP - RW - IF amplifier serial register **/
#define IFAMP_REG                     (0x0030u)
// IF amplifier current reference trim - RW [0:5]
# define IFAMP_BIAS_IFAMPI_MASK                   (0x003Fu)
# define IFAMP_BIAS_IFAMPI_BIT                    (0)
# define IFAMP_BIAS_IFAMPI_BITS                   (6)
// IF amplifier voltage reference trim - RW [6:11]
# define IFAMP_BIAS_IFAMPV_MASK                   (0x0FC0u)
# define IFAMP_BIAS_IFAMPV_BIT                    (6)
# define IFAMP_BIAS_IFAMPV_BITS                   (6)
// Not used - RW [12:15]
# define IFAMP_UNUSED_MASK                        (0xF000u)
# define IFAMP_UNUSED_BIT                         (12)
# define IFAMP_UNUSED_BITS                        (4)

/** RXADC_H - RW - RX adc serial register **/
#define RXADC_H_REG                   (0x0040u)
// rx adc current reference trim - RW [0:5]
# define RXADC_H_BIAS_RXADCI_MASK                 (0x003Fu)
# define RXADC_H_BIAS_RXADCI_BIT                  (0)
# define RXADC_H_BIAS_RXADCI_BITS                 (6)
// rx adc voltage reference trim - RW [6:11]
# define RXADC_H_BIAS_RXADCV_MASK                 (0x0FC0u)
# define RXADC_H_BIAS_RXADCV_BIT                  (6)
# define RXADC_H_BIAS_RXADCV_BITS                 (6)
// rx adc bias trim - RW [12:13]
# define RXADC_H_BIAS_TRIM_MASK                   (0x3000u)
# define RXADC_H_BIAS_TRIM_BIT                    (12)
# define RXADC_H_BIAS_TRIM_BITS                   (2)
// Not used - RW [14:15]
# define RXADC_H_UNUSED_MASK                      (0xC000u)
# define RXADC_H_UNUSED_BIT                       (14)
# define RXADC_H_UNUSED_BITS                      (2)

/** RXADC_L - RW - RX adc serial register **/
#define RXADC_L_REG                   (0x0041u)
// rx adc jam test - RW [0:9]
# define RXADC_L_RX_ADC_JAM_MASK                  (0x03FFu)
# define RXADC_L_RX_ADC_JAM_BIT                   (0)
# define RXADC_L_RX_ADC_JAM_BITS                  (10)
// rx adc gain (1=high) - RW [10:10]
# define RXADC_L_RX_ADC_GAIN_MASK                 (0x0400u)
# define RXADC_L_RX_ADC_GAIN_BIT                  (10)
# define RXADC_L_RX_ADC_GAIN_BITS                 (1)
// Not used - RW [11:15]
# define RXADC_L_UNUSED_MASK                      (0xF800u)
# define RXADC_L_UNUSED_BIT                       (11)
# define RXADC_L_UNUSED_BITS                      (5)

/** PRESCALER - RW - Prescaler serial register **/
#define PRESCALER_REG                 (0x0060u)
// Prescaler current reference trim - RW [0:5]
# define PRESCALER_BIAS_PRESCALERI_MASK           (0x003Fu)
# define PRESCALER_BIAS_PRESCALERI_BIT            (0)
# define PRESCALER_BIAS_PRESCALERI_BITS           (6)
// Prescaler bias trim LSBs - RW [6:7]
# define PRESCALER_BIAS_TRIM_MASK                 (0x00C0u)
# define PRESCALER_BIAS_TRIM_BIT                  (6)
# define PRESCALER_BIAS_TRIM_BITS                 (2)
// Inverted MSB of prescler bias trim - RW [8:8]
# define PRESCALER_BIAS_TRIM_B_MASK               (0x0100u)
# define PRESCALER_BIAS_TRIM_B_BIT                (8)
# define PRESCALER_BIAS_TRIM_B_BITS               (1)
// LO divider current reference trim - RW [9:14]
# define PRESCALER_BIAS_DIVIDERI_MASK             (0x7E00u)
# define PRESCALER_BIAS_DIVIDERI_BIT              (9)
# define PRESCALER_BIAS_DIVIDERI_BITS             (6)
// Force prescaler to divide by 56 - RW [15:15]
# define PRESCALER_MC_FORCE_MASK                  (0x8000u)
# define PRESCALER_MC_FORCE_BIT                   (15)
# define PRESCALER_MC_FORCE_BITS                  (1)

/** PHASE_DETECTOR - RW - Phase detector serial register **/
#define PHASE_DETECTOR_REG            (0x0070u)
// PFD current reference trim - RW [0:5]
# define PHASE_DETECTOR_BIAS_PFDI_MASK            (0x003Fu)
# define PHASE_DETECTOR_BIAS_PFDI_BIT             (0)
# define PHASE_DETECTOR_BIAS_PFDI_BITS            (6)
// inverted phase detector bias trim - RW [6:8]
# define PHASE_DETECTOR_BIAS_TRIM_B_MASK          (0x01C0u)
# define PHASE_DETECTOR_BIAS_TRIM_B_BIT           (6)
# define PHASE_DETECTOR_BIAS_TRIM_B_BITS          (3)
// Not used - RW [9:15]
# define PHASE_DETECTOR_UNUSED_MASK               (0xFE00u)
# define PHASE_DETECTOR_UNUSED_BIT                (9)
# define PHASE_DETECTOR_UNUSED_BITS               (7)

/** VCO_H - RW - VCO serial register **/
#define VCO_H_REG                     (0x0080u)
// VCO bias current trim - RW [0:4]
# define VCO_H_BIAS_TRIM_VCO_MASK                 (0x001Fu)
# define VCO_H_BIAS_TRIM_VCO_BIT                  (0)
# define VCO_H_BIAS_TRIM_VCO_BITS                 (5)
// Inverted MSB of VCO bias current trim - RW [5:5]
# define VCO_H_BIAS_TRIM_VCO_B_MASK               (0x0020u)
# define VCO_H_BIAS_TRIM_VCO_B_BIT                (5)
# define VCO_H_BIAS_TRIM_VCO_B_BITS               (1)
// VCO tune value - RW [6:11]
# define VCO_H_TUNE_VCO_MASK                      (0x0FC0u)
# define VCO_H_TUNE_VCO_BIT                       (6)
# define VCO_H_TUNE_VCO_BITS                      (6)
// Not used - RW [12:15]
# define VCO_H_UNUSED_MASK                        (0xF000u)
# define VCO_H_UNUSED_BIT                         (12)
# define VCO_H_UNUSED_BITS                        (4)

/** VCO_L - RW - VCO serial register **/
#define VCO_L_REG                     (0x0081u)
// VCO current reference trim - RW [0:5]
# define VCO_L_BIAS_VCOI_MASK                     (0x003Fu)
# define VCO_L_BIAS_VCOI_BIT                      (0)
# define VCO_L_BIAS_VCOI_BITS                     (6)
// VCO voltage reference trim - RW [6:11]
# define VCO_L_BIAS_VCOV_MASK                     (0x0FC0u)
# define VCO_L_BIAS_VCOV_BIT                      (6)
# define VCO_L_BIAS_VCOV_BITS                     (6)
// Not used - RW [12:15]
# define VCO_L_UNUSED_MASK                        (0xF000u)
# define VCO_L_UNUSED_BIT                         (12)
# define VCO_L_UNUSED_BITS                        (4)

/** LOOP_FILTER - RW - Loop filter serial register **/
#define LOOP_FILTER_REG               (0x0090u)
// Loop current reference trim - RW [0:5]
# define LOOP_FILTER_BIAS_LOOPI_MASK              (0x003Fu)
# define LOOP_FILTER_BIAS_LOOPI_BIT               (0)
# define LOOP_FILTER_BIAS_LOOPI_BITS              (6)
// Loop voltage reference trim - RW [6:11]
# define LOOP_FILTER_BIAS_LOOPV_MASK              (0x0FC0u)
# define LOOP_FILTER_BIAS_LOOPV_BIT               (6)
# define LOOP_FILTER_BIAS_LOOPV_BITS              (6)
// Open the VCO loop (for DAC cal) - RW [12:12]
# define LOOP_FILTER_OPEN_VCO_LOOP_MASK           (0x1000u)
# define LOOP_FILTER_OPEN_VCO_LOOP_BIT            (12)
# define LOOP_FILTER_OPEN_VCO_LOOP_BITS           (1)
// Sythnesizer reset - RW [13:13]
# define LOOP_FILTER_SYNTH_RESET_MASK             (0x2000u)
# define LOOP_FILTER_SYNTH_RESET_BIT              (13)
# define LOOP_FILTER_SYNTH_RESET_BITS             (1)
// Not used - RW [14:15]
# define LOOP_FILTER_UNUSED_MASK                  (0xC000u)
# define LOOP_FILTER_UNUSED_BIT                   (14)
# define LOOP_FILTER_UNUSED_BITS                  (2)

/** PA - RW - PA serial register **/
#define PA_REG                        (0x00A0u)
// PA current reference trim - RW [0:5]
# define PA_BIAS_PAI_MASK                         (0x003Fu)
# define PA_BIAS_PAI_BIT                          (0)
# define PA_BIAS_PAI_BITS                         (6)
// PA output select (0=lna pins, 1=pa pins) - RW [6:6]
# define PA_PA_OUT_SEL_MASK                       (0x0040u)
# define PA_PA_OUT_SEL_BIT                        (6)
# define PA_PA_OUT_SEL_BITS                       (1)
// PA high bias control for pa buffer (0=low,1=high) - RW [7:7]
# define PA_PA_HIGH_BIAS_MASK                     (0x0080u)
# define PA_PA_HIGH_BIAS_BIT                      (7)
# define PA_PA_HIGH_BIAS_BITS                     (1)
// Not used - RW [8:15]
# define PA_UNUSED_MASK                           (0xFF00u)
# define PA_UNUSED_BIT                            (8)
# define PA_UNUSED_BITS                           (8)

/** MODULATION_DAC_H - RW - Modulcation DAC serial register **/
#define MODULATION_DAC_H_REG          (0x00B0u)
// mod DAC current reference trim - RW [0:5]
# define MODULATION_DAC_H_BIAS_MODACI_MASK        (0x003Fu)
# define MODULATION_DAC_H_BIAS_MODACI_BIT         (0)
# define MODULATION_DAC_H_BIAS_MODACI_BITS        (6)
// mod DAC voltage reference trim - RW [6:11]
# define MODULATION_DAC_H_BIAS_MODACV_MASK        (0x0FC0u)
# define MODULATION_DAC_H_BIAS_MODACV_BIT         (6)
# define MODULATION_DAC_H_BIAS_MODACV_BITS        (6)
// Not used - RW [12:15]
# define MODULATION_DAC_H_UNUSED_MASK             (0xF000u)
# define MODULATION_DAC_H_UNUSED_BIT              (12)
# define MODULATION_DAC_H_UNUSED_BITS             (4)

/** MODULATION_DAC_L - RW - Modulcation DAC serial register **/
#define MODULATION_DAC_L_REG          (0x00B1u)
// Modualtion deviation setting - RW [0:5]
# define MODULATION_DAC_L_ADJUST_MODULATION_MASK  (0x003Fu)
# define MODULATION_DAC_L_ADJUST_MODULATION_BIT   (0)
# define MODULATION_DAC_L_ADJUST_MODULATION_BITS  (6)
// Not used - RW [6:15]
# define MODULATION_DAC_L_UNUSED_MASK             (0xFFC0u)
# define MODULATION_DAC_L_UNUSED_BIT              (6)
# define MODULATION_DAC_L_UNUSED_BITS             (10)

/** AUXADC_H - RW - Auxiliary adc serial register **/
#define AUXADC_H_REG                  (0x00C0u)
// Aux adc current reference trim - RW [0:5]
# define AUXADC_H_BIAS_AUXADCI_MASK               (0x003Fu)
# define AUXADC_H_BIAS_AUXADCI_BIT                (0)
# define AUXADC_H_BIAS_AUXADCI_BITS               (6)
// Aux adc voltage reference trim - RW [6:11]
# define AUXADC_H_BIAS_AUXADCV_MASK               (0x0FC0u)
# define AUXADC_H_BIAS_AUXADCV_BIT                (6)
# define AUXADC_H_BIAS_AUXADCV_BITS               (6)
// Not used - RW [12:15]
# define AUXADC_H_UNUSED_MASK                     (0xF000u)
# define AUXADC_H_UNUSED_BIT                      (12)
# define AUXADC_H_UNUSED_BITS                     (4)

/** IQ_BUFFER - RW - IQ buffer serial register **/
#define IQ_BUFFER_REG                 (0x00E0u)
// IQ buffer current reference trim - RW [0:5]
# define IQ_BUFFER_BIAS_IQBUFFI_MASK              (0x003Fu)
# define IQ_BUFFER_BIAS_IQBUFFI_BIT               (0)
# define IQ_BUFFER_BIAS_IQBUFFI_BITS              (6)
// Not used - RW [6:15]
# define IQ_BUFFER_UNUSED_MASK                    (0xFFC0u)
# define IQ_BUFFER_UNUSED_BIT                     (6)
# define IQ_BUFFER_UNUSED_BITS                    (10)

/** BIAS_MASTER - RW - Bias master serial register **/
#define BIAS_MASTER_REG               (0x00F0u)
// Master current reference trim - RW [0:5]
# define BIAS_MASTER_BIAS_MASTBIASI_MASK          (0x003Fu)
# define BIAS_MASTER_BIAS_MASTBIASI_BIT           (0)
# define BIAS_MASTER_BIAS_MASTBIASI_BITS          (6)
// Master voltage reference trim - RW [6:11]
# define BIAS_MASTER_BIAS_MASTBIASV_MASK          (0x0FC0u)
# define BIAS_MASTER_BIAS_MASTBIASV_BIT           (6)
# define BIAS_MASTER_BIAS_MASTBIASV_BITS          (6)
// Set high by software when bias calibration has been run, otherwise zero - RW [12:12]
# define BIAS_MASTER_CAL_DONE_MASK                (0x1000u)
# define BIAS_MASTER_CAL_DONE_BIT                 (12)
# define BIAS_MASTER_CAL_DONE_BITS                (1)
// Not used - RW [13:14]
# define BIAS_MASTER_UNUSED_MASK                  (0x6000u)
# define BIAS_MASTER_UNUSED_BIT                   (13)
# define BIAS_MASTER_UNUSED_BITS                  (2)
// always reads back a one to signify revD, writing to this bit has no effect - RW [15:15]
# define BIAS_MASTER_MSB_HIGH_MASK                (0x8000u)
# define BIAS_MASTER_MSB_HIGH_BIT                 (15)
# define BIAS_MASTER_MSB_HIGH_BITS                (1)

#endif//__KRAKATOA_REGS_INDIRECT_H__
