/***************************************************************************//**
 * @file
 * @brief Header file for RAIL BTC helper functionality available to RailApp
 *******************************************************************************
 * # License
 * <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#ifndef __RAILAPP_BTC_H__
#define __RAILAPP_BTC_H__

#include <stdint.h>
#include <stdbool.h>
#include "rail_types.h"
#include "sl_rail_btc.h"

#ifdef __cplusplus
extern "C" {
#endif

/***************************************************************************/
/* Generic helper APIs (usable by both CLI- and RPC-based applications)    */
/***************************************************************************/

/**
 * Initialize the BTC hardware block.
 *
 * @param accessWord0 First word of the 64-bit sync word.
 * @param accessWord1 Second word of the 64-bit sync word.
 * @param bdAddr5     The MSByte of the device address.
 */
void RAILAPP_BTC_HW_Init(uint32_t accessWord0,
                         uint32_t accessWord1,
                         uint8_t  bdAddr5);

/**
 * Configure whitening for BTC.
 *
 * @param seed Whitening LFSR seed value.
 */
void RAILAPP_BTC_SetWhitening(uint8_t seed);

/**
 * Prepare a TX or RX transfer according to @p packetType.
 *
 * @param isRx        true for RX preparation, false for TX.
 * @param packetType  BTC packet type (see RAIL_BtcPacketType_t).
 * @param payloadLen  Payload length in bytes (where applicable).
 * @param encryption  0: none, 1: E0, 2: AES.
 *
 * @return Byte offset within the global TX FIFO buffer (``pktData``) at which
 *         the BTC payload begins.  The offset can be used by higher-level
 *         tooling (e.g. host-side test helpers) to patch payload or CRC bytes
 *         after the BTC packet header has been generated by this helper.
 *         A return value of 0 indicates that no payload area was reserved
 *         (e.g. for ID or NULL packets) or that the packet type was
 *         unsupported.
 */
uint32_t RAILAPP_BTC_Prepare(bool     isRx,
                             uint8_t  packetType,
                             uint16_t payloadLen,
                             uint8_t  encryption);

/** Convenience helper to configure E0 encryption. */
void RAILAPP_BTC_SetE0Encryption(void);

/** A portion of RAILAPP_BTC_SetE0Encryption that is required per packet. */
void RAILAPP_BTC_SetE0EncryptionMasterClock(void);

/** Convenience helper to configure AES encryption. */
void RAILAPP_BTC_SetAESEncryption(void);

/** A portion of RAILAPP_BTC_SetAESEncryption that is required per packet. */
void RAILAPP_BTC_SetAESEncryptionNonce(void);

/** Convenience helper to configure continuous Tx. */
void RAILAPP_BTC_configureContinuousTx(sl_rail_btc_continuous_rate_t rate);

#ifdef __cplusplus
}
#endif

#endif // __RAILAPP_BTC_H__
